/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright " converted by maumax AKA Foreverold"
#property link      " http://www.forex-tsd.com"

extern double Lots = 1.0;
extern double StopLoss = 40.0;
extern double TakeProfit = 0.0;
extern double TrailingStop = 0.0;
extern double Slippage = 5.0;
extern double startHourOfDay = 0.0;
extern double endofDAY = 23.0;
extern double beginer = 64.0;
extern double periodtotake = 64.0;
int g_datetime_148;
double gda_unused_152[];
double gda_unused_156[];

int MOrderDelete(int a_ticket_0) {
   g_datetime_148 = TimeCurrent();
   return (OrderDelete(a_ticket_0));
}

int MOrderSend(string a_symbol_0, int a_cmd_8, double a_lots_12, double a_price_20, int a_slippage_28, double a_price_32, double a_price_40, string a_comment_48 = "", int a_magic_56 = 0, int a_datetime_60 = 0, color a_color_64 = -1) {
   g_datetime_148 = TimeCurrent();
   a_price_20 = MathRound(10000.0 * a_price_20) / 10000.0;
   a_price_32 = MathRound(10000.0 * a_price_32) / 10000.0;
   a_price_40 = MathRound(10000.0 * a_price_40) / 10000.0;
   return (OrderSend(a_symbol_0, a_cmd_8, a_lots_12, a_price_20, a_slippage_28, a_price_32, a_price_40, a_comment_48, a_magic_56, a_datetime_60, a_color_64));
}

int OrderValueTicket(int a_pos_0) {
   OrderSelect(a_pos_0, SELECT_BY_POS);
   return (OrderTicket());
}

int OrderValueType(int a_pos_0) {
   OrderSelect(a_pos_0, SELECT_BY_POS);
   return (OrderType());
}

double OrderValueLots(int a_pos_0) {
   OrderSelect(a_pos_0, SELECT_BY_POS);
   return (OrderLots());
}

string OrderValueSymbol(int a_pos_0) {
   OrderSelect(a_pos_0, SELECT_BY_POS);
   return (OrderSymbol());
}

int start() {
   int l_count_0 = 0;
   double l_lots_4 = 0;
   double ld_unused_12 = 0;
   double ld_unused_20 = 0;
   double ld_28 = 0;
   double ld_36 = 0;
   double ld_44 = 0;
   double ld_unused_52 = 0;
   double ld_unused_60 = 0;
   double ld_unused_68 = 0;
   double ld_unused_76 = 0;
   double ld_84 = 0;
   double l_low_92 = 0;
   double l_high_100 = 0;
   double ld_108 = 0;
   double ld_116 = 0;
   double ld_124 = 0;
   double ld_132 = 0;
   double ld_140 = 0;
   double ld_148 = 0;
   double ld_156 = 0;
   double ld_164 = 0;
   double ld_172 = 0;
   double ld_180 = 0;
   double ld_188 = 0;
   double ld_196 = 0;
   double ld_204 = 0;
   double ld_212 = 0;
   double ld_220 = 0;
   double ld_228 = 0;
   double ld_236 = 0;
   double ld_244 = 0;
   double ld_252 = 0;
   double ld_260 = 0;
   double ld_268 = 0;
   double ld_276 = 0;
   double ld_284 = 0;
   double ld_292 = 0;
   double ld_300 = 0;
   double ld_308 = 0;
   double ld_316 = 0;
   double ld_324 = 0;
   double ld_332 = 0;
   double ld_340 = 0;
   double ld_348 = 0;
   double ld_356 = 0;
   double ld_364 = 0;
   ld_28 = 0;
   l_lots_4 = Lots;
   for (l_count_0 = 1; l_count_0 <= OrdersTotal(); l_count_0++) {
      if (OrderValueSymbol(l_count_0) == Symbol()) {
         ld_28++;
         if (OrderValueType(l_count_0) == 0) {
            if (Hour() == endofDAY) {
               OrderClose(OrderValueTicket(l_count_0), OrderValueLots(l_count_0), Bid, Slippage, Red);
               return (0);
            }
            ld_36 = 0;
         }
         if (OrderValueType(l_count_0) == 1) {
            if (Hour() == endofDAY) {
               OrderClose(OrderValueTicket(l_count_0), OrderValueLots(l_count_0), Ask, Slippage, Red);
               return (0);
            }
            ld_44 = 0;
         }
      }
   }
   if (Hour() == endofDAY) {
      if (ld_36 == 1.0) {
         for (l_count_0 = 1; l_count_0 <= OrdersTotal(); l_count_0++) {
            if (OrderValueSymbol(l_count_0) == Symbol() && OrderValueType(l_count_0) == 3) {
               MOrderDelete(OrderValueTicket(l_count_0));
               return (0);
            }
         }
      }
   }
   if (Hour() == endofDAY) {
      if (ld_44 == 1.0) {
         for (l_count_0 = 1; l_count_0 <= OrdersTotal(); l_count_0++) {
            if (OrderValueSymbol(l_count_0) == Symbol() && OrderValueType(l_count_0) == 2) {
               MOrderDelete(OrderValueTicket(l_count_0));
               return (0);
            }
         }
      }
   }
   l_low_92 = Low[iLowest(NULL, 0, MODE_LOW, beginer, periodtotake)];
   l_high_100 = High[iHighest(NULL, 0, MODE_HIGH, beginer, periodtotake)];
   if (l_high_100 <= 250000.0 && l_high_100 > 25000.0) ld_108 = 100000;
   else {
      if (l_high_100 <= 25000.0 && l_high_100 > 2500.0) ld_108 = 10000;
      else {
         if (l_high_100 <= 2500.0 && l_high_100 > 250.0) ld_108 = 1000;
         else {
            if (l_high_100 <= 250.0 && l_high_100 > 25.0) ld_108 = 100;
            else {
               if (l_high_100 <= 25.0 && l_high_100 > 12.5) ld_108 = 12.5;
               else {
                  if (l_high_100 <= 12.5 && l_high_100 > 6.25) ld_108 = 12.5;
                  else {
                     if (l_high_100 <= 6.25 && l_high_100 > 3.125) ld_108 = 6.25;
                     else {
                        if (l_high_100 <= 3.125 && l_high_100 > 1.5625) ld_108 = 3.125;
                        else {
                           if (l_high_100 <= 1.5625 && l_high_100 > 0.390625) ld_108 = 1.5625;
                           else
                              if (l_high_100 <= 0.390625 && l_high_100 > 0.0) ld_108 = 0.1953125;
                        }
                     }
                  }
               }
            }
         }
      }
   }
   ld_228 = l_high_100 - l_low_92;
   ld_84 = MathFloor(MathLog(ld_108 / ld_228) / MathLog(2));
   ld_236 = ld_108 * MathPow(0.5, ld_84);
   ld_244 = MathFloor(l_low_92 / ld_236) * ld_236;
   if (ld_244 + ld_236 > l_high_100) ld_252 = ld_244 + ld_236;
   else ld_252 = ld_244 + 2.0 * ld_236;
   if (l_low_92 >= 0.0 * (ld_252 - ld_244) + ld_244 && l_high_100 <= 0.0 * (ld_252 - ld_244) + ld_244) ld_284 = ld_244 + (ld_252 - ld_244) / 2.0;
   else ld_284 = 0;
   if (l_low_92 >= ld_244 - (ld_252 - ld_244) / 8.0 && l_high_100 <= 0.0 * (ld_252 - ld_244) + ld_244 && ld_284 == 0.0) ld_276 = ld_244 + (ld_252 - ld_244) / 2.0;
   else ld_276 = 0;
   if (l_low_92 >= ld_244 + 7.0 * (ld_252 - ld_244) / 16.0 && l_high_100 <= 0.0 * (ld_252 - ld_244) + ld_244) ld_300 = ld_244 + 3.0 * (ld_252 - ld_244) / 4.0;
   else ld_300 = 0;
   if (l_low_92 >= ld_244 + 3.0 * (ld_252 - ld_244) / 8.0 && l_high_100 <= 1.0 * (ld_252 - ld_244) + ld_244 && ld_300 == 0.0) ld_308 = ld_252;
   else ld_308 = 0;
   if (l_low_92 >= ld_244 + (ld_252 - ld_244) / 8.0 && l_high_100 <= 0.0 * (ld_252 - ld_244) + ld_244 && ld_276 == 0.0 && ld_284 == 0.0 && ld_300 == 0.0 && ld_308 == 0.0) ld_292 = ld_244 + 3.0 * (ld_252 - ld_244) / 4.0;
   else ld_292 = 0;
   if (ld_276 + ld_284 + ld_292 + ld_300 + ld_308 == 0.0) ld_316 = ld_252;
   else ld_316 = 0;
   ld_260 = ld_276 + ld_284 + ld_292 + ld_300 + ld_308 + ld_316;
   if (ld_276 > 0.0) ld_324 = ld_244;
   else ld_324 = 0;
   if (ld_284 > 0.0) ld_332 = ld_244 + (ld_252 - ld_244) / 4.0;
   else ld_332 = 0;
   if (ld_292 > 0.0) ld_340 = ld_244 + (ld_252 - ld_244) / 4.0;
   else ld_340 = 0;
   if (ld_300 > 0.0) ld_348 = ld_244 + (ld_252 - ld_244) / 2.0;
   else ld_348 = 0;
   if (ld_308 > 0.0) ld_356 = ld_244 + (ld_252 - ld_244) / 2.0;
   else ld_356 = 0;
   if (ld_260 > 0.0 && ld_324 + ld_332 + ld_340 + ld_348 + ld_356 == 0.0) ld_364 = ld_244;
   else ld_364 = 0;
   ld_268 = ld_324 + ld_332 + ld_340 + ld_348 + ld_356 + ld_364;
   ld_116 = (ld_260 - ld_268) / 8.0;
   ld_124 = ld_268 - 2.0 * ld_116;
   ld_132 = ld_268 - ld_116;
   ld_140 = ld_268;
   ld_148 = ld_268 + ld_116;
   ld_156 = ld_268 + 2.0 * ld_116;
   ld_164 = ld_268 + 3.0 * ld_116;
   ld_172 = ld_268 + 4.0 * ld_116;
   ld_180 = ld_268 + 5.0 * ld_116;
   ld_188 = ld_268 + 6.0 * ld_116;
   ld_196 = ld_268 + 7.0 * ld_116;
   ld_204 = ld_268 + 8.0 * ld_116;
   ld_220 = ld_268 + 9.0 * ld_116;
   ld_212 = ld_268 + 10.0 * ld_116;
   Comment(" PLACE A BUY ORDER AT ", ld_140, "  PLACE A SELL ORDER AT ", ld_204);
   if (Open[1] < ld_140) {
      if (Hour() > startHourOfDay && Hour() < endofDAY && ld_28 < 1.0 && ld_36 == 0.0) {
         ld_36 = 2;
         MOrderSend(Symbol(), OP_BUYSTOP, l_lots_4, ld_140, Slippage, ld_140 - StopLoss * Point, ld_172, "", 16384, 0, Blue);
         return (0);
      }
   }
   if (Open[1] > ld_140) {
      if (Hour() > startHourOfDay && Hour() < endofDAY && ld_28 < 1.0 && ld_36 == 0.0) {
         ld_36 = 2;
         MOrderSend(Symbol(), OP_BUYLIMIT, l_lots_4, ld_140, Slippage, ld_140 - StopLoss * Point, ld_172, "", 16384, 0, Blue);
         return (0);
      }
   }
   if (Open[1] > ld_204) {
      if (Hour() > startHourOfDay && Hour() < endofDAY && ld_28 == 1.0 && ld_44 == 0.0 && ld_36 > 0.0) {
         ld_44 = 2;
         MOrderSend(Symbol(), OP_SELLSTOP, l_lots_4, ld_204, Slippage, ld_204 + StopLoss * Point, ld_172, "", 16384, 0, Red);
         return (0);
      }
   }
   if (Open[1] < ld_204) {
      if (Hour() > startHourOfDay && Hour() < endofDAY && ld_28 == 1.0 && ld_44 == 0.0 && ld_36 > 0.0) {
         ld_44 = 2;
         MOrderSend(Symbol(), OP_SELLLIMIT, l_lots_4, ld_204, Slippage, ld_204 + StopLoss * Point, ld_172, "", 16384, 0, Red);
         return (0);
      }
   }
   return (0);
}
