/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "Auto Harmonic Patterns by Barry Stander "
#property link      "http://www.4Africa.net/4meta/"

#property indicator_chart_window
#property indicator_buffers 8
#property indicator_color1 Red
#property indicator_color2 Blue
#property indicator_color3 Green
#property indicator_color4 Yellow
#property indicator_color5 Brown
#property indicator_color6 Black
#property indicator_color7 Orange
#property indicator_color8 DarkViolet

string gs_76 = "Auto Harmonic Patterns by Barry Stander --- ForexWinners.Net ";
double gd_84 = 1420245777.0;
extern int HP_Predict_Pattern = 1;
extern int Show_Target_Fibo_P = 1;
extern int Show_Old_Pattern = 1;
extern int Show_Target_Fibo_Old = 1;
int gi_108 = 1;
int gi_112 = 0;
int gi_116 = 0;
int gi_120 = 1;
extern int Histo = 30;
double gd_128 = 161.0;
double gd_136 = 127.0;
int g_width_144 = 2;
int g_fontsize_148 = 15;
int g_fontsize_152 = 10;
int gi_156 = 0;
int gi_160 = 0;
int gi_unused_164 = 0;
int gi_168 = 0;
int gi_172 = 0;
int gi_176 = 1;
int gi_unused_180 = 0;
int gi_unused_184;
int gi_188;
int gi_192 = 2;
int g_count_196;
double g_ibuf_200[];
double g_ibuf_204[];
double g_ibuf_208[];
double g_ibuf_212[];
double g_ibuf_216[];
double g_ibuf_220[];
int gi_224;
double g_ibuf_228[];
double gda_232[];
int gia_236[501];
double gda_240[501];
double gda_unused_244[];
int gia_248[2];
double gda_252[2];
int gia_256[2];
double gda_260[2];
int gia_unused_264[10];
double gda_unused_268[10];
int gia_272[10];
double gda_276[10];
int g_count_280;
int g_count_284;
int g_count_288;
int g_count_292;
int gi_296 = 0;
int gi_300 = 0;
int gi_unused_304 = 0;
int gi_unused_308 = 0;
string gs_312;

int DeleteObj_preD() {
   ObjectDelete("HarPat0mp");
   ObjectDelete("HarPat1mp");
   ObjectDelete("HarPat2mp");
   ObjectDelete("HarPat3mp");
   ObjectDelete("HarPat4mp");
   ObjectDelete("HarPat5mp");
   ObjectDelete("HarPat6mp");
   ObjectDelete("HarPat7mp");
   ObjectDelete("HarPat8mp");
   ObjectDelete("HarPat9mp");
   ObjectDelete("HarPat10mp");
   ObjectDelete("HarPat11mp");
   ObjectDelete("HarPat12mp");
   ObjectDelete("HarPat13mp");
   ObjectDelete("HarPat14mp");
   ObjectDelete("HarPat15mp");
   ObjectDelete("HarPat16mp");
   ObjectDelete("HarPat17mp");
   ObjectDelete("HarPat18mp");
   ObjectDelete("HarPat19mp");
   ObjectDelete("HarPat20mp");
   ObjectDelete("HarPat21mp");
   ObjectDelete("HarPat22mp");
   ObjectDelete("HarPat0wp");
   ObjectDelete("HarPat1wp");
   ObjectDelete("HarPat2wp");
   ObjectDelete("HarPat3wp");
   ObjectDelete("HarPat4wp");
   ObjectDelete("HarPat5wp");
   ObjectDelete("HarPat6wp");
   ObjectDelete("HarPat7wp");
   ObjectDelete("HarPat8wp");
   ObjectDelete("HarPat9wp");
   ObjectDelete("HarPat10wp");
   ObjectDelete("HarPat11wp");
   ObjectDelete("HarPat12wp");
   ObjectDelete("HarPat13wp");
   ObjectDelete("HarPat14wp");
   ObjectDelete("HarPat15wp");
   ObjectDelete("HarPat16wp");
   ObjectDelete("HarPat17wp");
   ObjectDelete("HarPat18wp");
   ObjectDelete("HarPat19wp");
   ObjectDelete("HarPat20wp");
   ObjectDelete("HarPat21wp");
   ObjectDelete("HarPat22wp");
   return (0);
}

int DeleteObj_old() {
   for (int l_count_0 = 0; l_count_0 <= Histo; l_count_0++) {
      ObjectDelete("HarPat0m" + l_count_0);
      ObjectDelete("HarPat1m" + l_count_0);
      ObjectDelete("HarPat2m" + l_count_0);
      ObjectDelete("HarPat3m" + l_count_0);
      ObjectDelete("HarPat4m" + l_count_0);
      ObjectDelete("HarPat5m" + l_count_0);
      ObjectDelete("HarPat6m" + l_count_0);
      ObjectDelete("HarPat7m" + l_count_0);
      ObjectDelete("HarPat8m" + l_count_0);
      ObjectDelete("HarPat9m" + l_count_0);
      ObjectDelete("HarPat10m" + l_count_0);
      ObjectDelete("HarPat11m" + l_count_0);
      ObjectDelete("HarPat12m" + l_count_0);
      ObjectDelete("HarPat13m" + l_count_0);
      ObjectDelete("HarPat14m" + l_count_0);
      ObjectDelete("HarPat15m" + l_count_0);
      ObjectDelete("HarPat16m" + l_count_0);
      ObjectDelete("HarPat17m" + l_count_0);
      ObjectDelete("HarPat18m" + l_count_0);
      ObjectDelete("HarPat19m" + l_count_0);
      ObjectDelete("HarPat21m" + l_count_0);
      ObjectDelete("HarPat22m" + l_count_0);
      ObjectDelete("HarPat0w" + l_count_0);
      ObjectDelete("HarPat1w" + l_count_0);
      ObjectDelete("HarPat2w" + l_count_0);
      ObjectDelete("HarPat3w" + l_count_0);
      ObjectDelete("HarPat4w" + l_count_0);
      ObjectDelete("HarPat5w" + l_count_0);
      ObjectDelete("HarPat6w" + l_count_0);
      ObjectDelete("HarPat7w" + l_count_0);
      ObjectDelete("HarPat8w" + l_count_0);
      ObjectDelete("HarPat9w" + l_count_0);
      ObjectDelete("HarPat10w" + l_count_0);
      ObjectDelete("HarPat11w" + l_count_0);
      ObjectDelete("HarPat12w" + l_count_0);
      ObjectDelete("HarPat13w" + l_count_0);
      ObjectDelete("HarPat14w" + l_count_0);
      ObjectDelete("HarPat15w" + l_count_0);
      ObjectDelete("HarPat16w" + l_count_0);
      ObjectDelete("HarPat17w" + l_count_0);
      ObjectDelete("HarPat18w" + l_count_0);
      ObjectDelete("HarPat19w" + l_count_0);
      ObjectDelete("HarPat21w" + l_count_0);
      ObjectDelete("HarPat22w" + l_count_0);
      ObjectDelete("HarPatHSm0" + l_count_0);
      ObjectDelete("HarPatHSm1" + l_count_0);
      ObjectDelete("HarPatHSm2" + l_count_0);
      ObjectDelete("HarPatHSm3" + l_count_0);
      ObjectDelete("HarPatHSm4" + l_count_0);
      ObjectDelete("HarPatHSm5" + l_count_0);
      ObjectDelete("HarPatHSw0" + l_count_0);
      ObjectDelete("HarPatHSw1" + l_count_0);
      ObjectDelete("HarPatHSw2" + l_count_0);
      ObjectDelete("HarPatHSw3" + l_count_0);
      ObjectDelete("HarPatHSw4" + l_count_0);
      ObjectDelete("HarPatHSw5" + l_count_0);
   }
   ObjectDelete("HarPat20m");
   ObjectDelete("HarPat20w");
   return (0);
}

int init() {
   Comment(gs_76);
   gi_unused_184 = 0;
   if (TimeCurrent() < gd_84 - 1.0) {
      IndicatorBuffers(8);
      SetIndexStyle(0, DRAW_NONE);
      SetIndexStyle(1, DRAW_NONE);
      SetIndexStyle(2, DRAW_NONE);
      SetIndexStyle(3, DRAW_NONE);
      SetIndexStyle(4, DRAW_NONE);
      SetIndexStyle(5, DRAW_NONE);
      SetIndexStyle(6, DRAW_NONE);
      SetIndexStyle(7, DRAW_NONE);
      if (gi_176 == 1) SetIndexStyle(0, DRAW_ARROW);
      SetIndexBuffer(0, g_ibuf_228);
      SetIndexBuffer(2, g_ibuf_200);
      SetIndexBuffer(3, g_ibuf_204);
      SetIndexBuffer(4, g_ibuf_208);
      SetIndexBuffer(5, g_ibuf_212);
      SetIndexBuffer(6, g_ibuf_216);
      SetIndexBuffer(7, g_ibuf_220);
      SetIndexLabel(0, "current");
      SetIndexLabel(1, "");
      SetIndexLabel(2, "bmode");
      SetIndexLabel(3, "b_D");
      SetIndexLabel(4, "b_C");
      SetIndexLabel(5, "smode");
      SetIndexLabel(6, "s_D");
      SetIndexLabel(7, "s_C");
      DeleteObj_preD();
      DeleteObj_old();
   }
   return (0);
}

int deinit() {
   DeleteObj_preD();
   DeleteObj_old();
   return (0);
}

int start() {
   double ld_0;
   double ld_8;
   double ld_16;
   double ld_24;
   double ld_32;
   double ld_40;
   double ld_48;
   double ld_56;
   double ld_64;
   double ld_72;
   double ld_80;
   double ld_88;
   double ld_96;
   double ld_104;
   double ld_112;
   double ld_120;
   double ld_128;
   double ld_136;
   double ld_144;
   double ld_152;
   double ld_160;
   double ld_168;
   double ld_176;
   double ld_184;
   double ld_192;
   double ld_200;
   double ld_208;
   double ld_216;
   double ld_224;
   double ld_232;
   double ld_240;
   double ld_248;
   double ld_256;
   g_count_196 = 0;
   for (int l_count_264 = 0; l_count_264 < Histo; l_count_264++) {
      ld_0 = ObjectGet("HarPat1m" + l_count_264, OBJPROP_PRICE1);
      ld_8 = ObjectGet("HarPat1m" + ((l_count_264 + 1)), OBJPROP_PRICE1);
      ld_16 = ObjectGet("HarPat1m" + ((l_count_264 + 2)), OBJPROP_PRICE1);
      ld_24 = ObjectGet("HarPat1m" + ((l_count_264 + 3)), OBJPROP_PRICE1);
      ld_32 = ObjectGet("HarPat1m" + ((l_count_264 + 4)), OBJPROP_PRICE1);
      ld_40 = ObjectGet("HarPat1w" + l_count_264, OBJPROP_PRICE1);
      ld_48 = ObjectGet("HarPat1w" + ((l_count_264 + 1)), OBJPROP_PRICE1);
      ld_56 = ObjectGet("HarPat1w" + ((l_count_264 + 2)), OBJPROP_PRICE1);
      ld_64 = ObjectGet("HarPat1w" + ((l_count_264 + 3)), OBJPROP_PRICE1);
      ld_72 = ObjectGet("HarPat1w" + ((l_count_264 + 4)), OBJPROP_PRICE1);
      if ((ld_0 == ld_8 && ld_0 > 0.0 && ld_8 > 0.0) || (ld_40 == ld_48 && ld_40 > 0.0 && ld_48 > 0.0) || (ld_0 == ld_16 && ld_0 > 0.0 && ld_16 > 0.0) || (ld_40 == ld_56 &&
         ld_40 > 0.0 && ld_56 > 0.0) || (ld_0 == ld_24 && ld_0 > 0.0 && ld_24 > 0.0) || (ld_40 == ld_64 && ld_40 > 0.0 && ld_64 > 0.0) || (ld_0 == ld_32 && ld_0 > 0.0 && ld_32 > 0.0) ||
         (ld_40 == ld_72 && ld_40 > 0.0 && ld_72 > 0.0)) g_count_196++;
   }
   if (g_count_196 > 0) {
      DeleteObj_preD();
      DeleteObj_old();
   }
   int li_268 = 0;
   int li_272 = 0;
   int li_276 = 2;
   double ld_280 = 0;
   double ld_288 = 0;
   int li_unused_296 = 0;
   g_ibuf_200[0] = 0;
   g_ibuf_204[0] = 0;
   g_ibuf_208[0] = 0;
   g_ibuf_212[0] = 0;
   g_ibuf_216[0] = 0;
   g_ibuf_220[0] = 0;
   gs_312 = "";
   if (Histo > 500) Histo = 500;
   if (Histo < 30) Histo = 30;
   gi_188 = 3 * Histo;
   if (TimeCurrent() > gd_84 + 5.0) {
   }
   int l_ind_counted_300 = IndicatorCounted();
   int li_304 = gi_188 - gi_192;
   if (li_304 > gi_192) li_304 = li_304 - gi_192 - 1;
   if (l_ind_counted_300 == 0) {
      DeleteObj_preD();
      DeleteObj_old();
   }
   while (li_304 > gi_192 - 1) {
      g_ibuf_228[li_304] = 0;
      ld_80 = Low[li_304];
      for (int li_308 = 1; li_308 <= gi_192; li_308++)
         if (Low[li_304 + li_308] < Low[li_304] || Low[li_304 - li_308] < Low[li_304]) ld_80 = 0;
      if (ld_80 > 0.0) {
         if (ld_288 != 0.0) {
            switch (li_276) {
            case 1:
               if (ld_80 < ld_288) {
                  g_ibuf_228[li_268] = ld_280;
                  gda_240[0] = g_ibuf_228[li_268];
                  gia_236[0] = li_268;
                  li_276 = 2;
               }
               break;
            case 2:
               if (ld_80 > ld_288) {
                  g_ibuf_228[li_272] = ld_288;
                  gda_240[0] = g_ibuf_228[li_272];
                  gia_236[0] = li_272;
                  li_276 = 1;
                  if (li_268 >= li_272) {
                     ld_280 = 0;
                     li_268 = 0;
                  }
               }
            }
         }
         ld_288 = ld_80;
         li_272 = li_304;
         gda_232[li_272] = ld_288;
      }
      ld_80 = High[li_304];
      for (li_308 = 1; li_308 <= gi_192; li_308++)
         if (High[li_304 + li_308] > High[li_304] || High[li_304 - li_308] > High[li_304]) ld_80 = 0;
      if (ld_80 > 0.0) {
         if (ld_280 != 0.0) {
            switch (li_276) {
            case 1:
               if (ld_80 < ld_280) {
                  g_ibuf_228[li_268] = ld_280;
                  gda_240[0] = g_ibuf_228[li_268];
                  gia_236[0] = li_268;
                  li_276 = 2;
                  if (li_272 >= li_268) {
                     ld_288 = 0;
                     li_272 = 0;
                  }
               }
               break;
            case 2:
               if (ld_80 > ld_280) {
                  g_ibuf_228[li_272] = ld_288;
                  gda_240[0] = g_ibuf_228[li_272];
                  gia_236[0] = li_272;
                  li_276 = 1;
               }
            }
         }
         ld_280 = ld_80;
         li_268 = li_304;
         gda_232[li_268] = ld_280;
      }
      if (gda_240[0] > 0.0 && gda_240[0] != gda_240[1]) {
         for (int li_320 = Histo; li_320 >= 0; li_320--) {
            gda_240[li_320] = gda_240[li_320 - 1];
            gia_236[li_320] = gia_236[li_320 - 1];
         }
      }
      li_304--;
   }
   if (li_276 == 1) {
      g_ibuf_228[li_268] = ld_280;
      gda_240[0] = g_ibuf_228[li_268];
      gia_236[0] = li_268;
   } else {
      g_ibuf_228[li_272] = ld_288;
      gda_240[0] = g_ibuf_228[li_272];
      gia_236[0] = li_272;
   }
   if (gda_240[0] > 0.0 && gda_240[0] != gda_240[1]) {
      for (int li_324 = Histo; li_324 >= 0; li_324--) {
         gda_240[li_324] = gda_240[li_324 - 1];
         gia_236[li_324] = gia_236[li_324 - 1];
      }
   }
   g_count_280 = 0;
   g_count_284 = 0;
   g_count_288 = 0;
   g_count_292 = 0;
   for (int l_count_328 = 0; l_count_328 < Histo; l_count_328++) {
      if (Show_Old_Pattern == 1) {
         if (gda_240[l_count_328 - 2] < gda_240[l_count_328 - 1] && gda_240[l_count_328 - 3] > gda_240[l_count_328 - 2] && gda_240[l_count_328 - 3] <= gda_240[l_count_328 - 1] &&
            gda_240[l_count_328 - 4] < gda_240[l_count_328 - 2] && gda_240[l_count_328 - 4] > 0.0 && gia_236[l_count_328 - 1] > gia_236[l_count_328 - 2] && gia_236[l_count_328 - 2] > gia_236[l_count_328 - 3] &&
            gia_236[l_count_328 - 3] > gia_236[l_count_328 - 4]) {
            g_count_280++;
            gi_unused_304 = 1;
            g_ibuf_200[gia_236[l_count_328 - 4]] = 1;
            g_ibuf_204[gia_236[l_count_328 - 4]] = gda_240[l_count_328 - 4];
            g_ibuf_208[gia_236[l_count_328 - 4]] = gda_240[l_count_328 - 3];
            gi_224 = l_count_328 - 1;
            if (gda_240[l_count_328 - 1] > gda_240[l_count_328 - 0] && gda_240[l_count_328 - 2] > gda_240[l_count_328 - 0] && gda_240[l_count_328 - 3] > gda_240[l_count_328 - 0] &&
               gda_240[l_count_328 - 0] > 0.0 && gia_236[l_count_328 - 0] > gia_236[l_count_328 - 1]) {
               gi_unused_304 = 2;
               g_ibuf_200[gia_236[l_count_328 - 4]] = 2;
               g_ibuf_204[gia_236[l_count_328 - 4]] = gda_240[l_count_328 - 4];
               g_ibuf_208[gia_236[l_count_328 - 4]] = gda_240[l_count_328 - 3];
               if (gi_120 == 1) {
                  ObjectCreate("HarPat21m" + g_count_280, OBJ_TRIANGLE, 0, Time[gia_236[l_count_328 - 0]], gda_240[l_count_328 - 0], Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1], Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2]);
                  ObjectCreate("HarPat22m" + g_count_280, OBJ_TRIANGLE, 0, Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2], Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3], Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
               }
               ObjectCreate("HarPat0m" + g_count_280, OBJ_TREND, 0, Time[gia_236[l_count_328 - 0]], gda_240[l_count_328 - 0], Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1]);
               ObjectCreate("HarPat14m" + g_count_280, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 0]], gda_240[l_count_328 - 0]);
               ObjectSetText("HarPat14m" + g_count_280, "      x   ", g_fontsize_148);
               ObjectCreate("HarPat15m" + g_count_280, OBJ_TREND, 0, Time[gia_236[l_count_328 - 0]], gda_240[l_count_328 - 0], Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2]);
               ObjectCreate("HarPat16m" + g_count_280, OBJ_TREND, 0, Time[gia_236[l_count_328 - 0]], gda_240[l_count_328 - 0], Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
               ObjectCreate("HarPat17m" + g_count_280, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 2] - (gia_236[l_count_328 - 2] - (gia_236[l_count_328 - 0])) / 2], gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 0])) / 2.0);
               ObjectCreate("HarPat18m" + g_count_280, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 0] - (gia_236[l_count_328 - 0] - (gia_236[l_count_328 - 4])) / 2], gda_240[l_count_328 - 0] - (gda_240[l_count_328 - 0] - (gda_240[l_count_328 - 4])) / 2.0);
               ld_88 = MathAbs(gda_240[l_count_328 - 1] - (gda_240[l_count_328 - 2])) / Point / (MathAbs(gda_240[l_count_328 - 1] - (gda_240[l_count_328 - 0])) / Point);
               ld_96 = MathAbs(gda_240[l_count_328 - 4] - (gda_240[l_count_328 - 1])) / Point / (MathAbs(gda_240[l_count_328 - 1] - (gda_240[l_count_328 - 0])) / Point);
               ObjectSetText("HarPat17m" + g_count_280, DoubleToStr(ld_88, 3), g_fontsize_152);
               ObjectSetText("HarPat18m" + g_count_280, DoubleToStr(ld_96, 3), g_fontsize_152);
               if (gi_116 == 1) ObjectCreate("HarPat19m" + g_count_280, OBJ_FIBO, 0, Time[gia_236[l_count_328 - 0]], gda_240[l_count_328 - 0], Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1]);
               gs_312 = " Buy at point D :  " + ((gda_240[l_count_328 - 4]));
            }
            if (ObjectFind("HarPat1m" + g_count_280) != 0) ObjectCreate("HarPat1m" + g_count_280, OBJ_TREND, 0, Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1], Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2]);
            ObjectCreate("HarPat2m" + g_count_280, OBJ_TREND, 0, Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2], Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3]);
            ObjectCreate("HarPat3m" + g_count_280, OBJ_TREND, 0, Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3], Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
            ObjectCreate("HarPat4m" + g_count_280, OBJ_TREND, 0, Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1], Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3]);
            ObjectCreate("HarPat5m" + g_count_280, OBJ_TREND, 0, Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2], Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
            ObjectCreate("HarPat6m" + g_count_280, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 1] - (gia_236[l_count_328 - 1] - (gia_236[l_count_328 - 3])) / 2], gda_240[l_count_328 - 1] - (gda_240[l_count_328 - 1] - (gda_240[l_count_328 - 3])) / 2.0);
            ObjectCreate("HarPat7m" + g_count_280, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 2] - (gia_236[l_count_328 - 2] - (gia_236[l_count_328 - 4])) / 2], gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 4])) / 2.0);
            ld_104 = MathAbs(gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 3])) / Point / (MathAbs(gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 1])) / Point + 0.0000001);
            ld_112 = MathAbs(gda_240[l_count_328 - 4] - (gda_240[l_count_328 - 1])) / Point / (MathAbs(gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 1])) / Point + 0.0000001);
            ObjectSetText("HarPat6m" + g_count_280, DoubleToStr(ld_104, 3), g_fontsize_152);
            ObjectSetText("HarPat7m" + g_count_280, DoubleToStr(ld_112, 3), g_fontsize_152);
            if (gi_116 == 1) {
               ObjectCreate("HarPat8m" + g_count_280, OBJ_FIBO, 0, Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1], Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
               ObjectCreate("HarPat9m" + g_count_280, OBJ_FIBO, 0, Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2], Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1]);
            }
            if (Show_Target_Fibo_Old == 1) ObjectCreate("HarPat20m", OBJ_FIBO, 0, Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3], Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
            ObjectCreate("HarPat10m" + g_count_280, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
            ObjectSetText("HarPat10m" + g_count_280, "       d   ", g_fontsize_148);
            ObjectCreate("HarPat11m" + g_count_280, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3]);
            ObjectSetText("HarPat11m" + g_count_280, "       c ", g_fontsize_148);
            ObjectCreate("HarPat12m" + g_count_280, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2]);
            ObjectSetText("HarPat12m" + g_count_280, "       b   ", g_fontsize_148);
            ObjectCreate("HarPat13m" + g_count_280, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1]);
            ObjectSetText("HarPat13m" + g_count_280, "      a  ", g_fontsize_148);
         }
         if (gda_240[l_count_328 - 2] > gda_240[l_count_328 - 1] && gda_240[l_count_328 - 3] < gda_240[l_count_328 - 2] && gda_240[l_count_328 - 3] >= gda_240[l_count_328 - 1] &&
            gda_240[l_count_328 - 4] > gda_240[l_count_328 - 2] && gda_240[l_count_328 - 4] > 0.0 && gia_236[l_count_328 - 1] > gia_236[l_count_328 - 2] && gia_236[l_count_328 - 2] > gia_236[l_count_328 - 3] &&
            gia_236[l_count_328 - 3] > gia_236[l_count_328 - 4]) {
            gi_unused_308 = 1;
            g_count_284++;
            g_ibuf_212[gia_236[l_count_328 - 4]] = 1;
            g_ibuf_216[gia_236[l_count_328 - 4]] = gda_240[l_count_328 - 4];
            g_ibuf_220[gia_236[l_count_328 - 4]] = gda_240[l_count_328 - 3];
            if (gda_240[l_count_328 - 1] < gda_240[l_count_328 - 0] && gda_240[l_count_328 - 2] < gda_240[l_count_328 - 0] && gda_240[l_count_328 - 3] < gda_240[l_count_328 - 0] &&
               gda_240[l_count_328 - 0] > 0.0 && gia_236[l_count_328 - 0] > gia_236[l_count_328 - 1]) {
               gi_unused_308 = 2;
               g_ibuf_212[gia_236[l_count_328 - 4]] = 2;
               g_ibuf_216[gia_236[l_count_328 - 4]] = gda_240[l_count_328 - 4];
               g_ibuf_220[gia_236[l_count_328 - 4]] = gda_240[l_count_328 - 3];
               if (gi_120 == 1) {
                  ObjectCreate("HarPat21w" + g_count_284, OBJ_TRIANGLE, 0, Time[gia_236[l_count_328 - 0]], gda_240[l_count_328 - 0], Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1], Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2]);
                  ObjectCreate("HarPat22w" + g_count_284, OBJ_TRIANGLE, 0, Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2], Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3], Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
               }
               ObjectCreate("HarPat0w" + g_count_284, OBJ_TREND, 0, Time[gia_236[l_count_328 - 0]], gda_240[l_count_328 - 0], Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1]);
               ObjectCreate("HarPat14w" + g_count_284, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 0]], gda_240[l_count_328 - 0]);
               ObjectSetText("HarPat14w" + g_count_284, "X     ", g_fontsize_148);
               ObjectCreate("HarPat15w" + g_count_284, OBJ_TREND, 0, Time[gia_236[l_count_328 - 0]], gda_240[l_count_328 - 0], Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2]);
               ObjectCreate("HarPat16w" + g_count_284, OBJ_TREND, 0, Time[gia_236[l_count_328 - 0]], gda_240[l_count_328 - 0], Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
               ObjectCreate("HarPat17w" + g_count_284, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 2] - (gia_236[l_count_328 - 2] - (gia_236[l_count_328 - 0])) / 2], gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 0])) / 2.0);
               ObjectCreate("HarPat18w" + g_count_284, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 0] - (gia_236[l_count_328 - 0] - (gia_236[l_count_328 - 4])) / 2], gda_240[l_count_328 - 0] - (gda_240[l_count_328 - 0] - (gda_240[l_count_328 - 4])) / 2.0);
               ld_120 = MathAbs(gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 1])) / Point / (MathAbs(gda_240[l_count_328 - 0] - (gda_240[l_count_328 - 1])) / Point);
               ld_128 = MathAbs(gda_240[l_count_328 - 4] - (gda_240[l_count_328 - 1])) / Point / (MathAbs(gda_240[l_count_328 - 0] - (gda_240[l_count_328 - 1])) / Point);
               ObjectSetText("HarPat17w" + g_count_284, DoubleToStr(ld_120, 3), g_fontsize_152);
               ObjectSetText("HarPat18w" + g_count_284, DoubleToStr(ld_128, 3), g_fontsize_152);
               if (gi_116 == 1) ObjectCreate("HarPat19w" + g_count_284, OBJ_FIBO, 0, Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1], Time[gia_236[l_count_328 - 0]], gda_240[l_count_328 - 0]);
               gs_312 = " Sell at point D :  " + ((gda_240[l_count_328 - 4]));
            }
            ObjectCreate("HarPat1w" + g_count_284, OBJ_TREND, 0, Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1], Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2]);
            ObjectCreate("HarPat2w" + g_count_284, OBJ_TREND, 0, Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2], Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3]);
            ObjectCreate("HarPat3w" + g_count_284, OBJ_TREND, 0, Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3], Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
            ObjectCreate("HarPat4w" + g_count_284, OBJ_TREND, 0, Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1], Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3]);
            ObjectCreate("HarPat5w" + g_count_284, OBJ_TREND, 0, Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2], Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
            ObjectCreate("HarPat6w" + g_count_284, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 1] - (gia_236[l_count_328 - 1] - (gia_236[l_count_328 - 3])) / 2], gda_240[l_count_328 - 1] - (gda_240[l_count_328 - 1] - (gda_240[l_count_328 - 3])) / 2.0);
            ObjectCreate("HarPat7w" + g_count_284, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 2] - (gia_236[l_count_328 - 2] - (gia_236[l_count_328 - 4])) / 2], gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 4])) / 2.0);
            ld_136 = MathAbs(gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 3])) / Point / (MathAbs(gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 1])) / Point + 0.0000001);
            ld_144 = MathAbs(gda_240[l_count_328 - 4] - (gda_240[l_count_328 - 1])) / Point / (MathAbs(gda_240[l_count_328 - 2] - (gda_240[l_count_328 - 1])) / Point + 0.0000001);
            ObjectSetText("HarPat6w" + g_count_284, DoubleToStr(ld_136, 3), g_fontsize_152);
            ObjectSetText("HarPat7w" + g_count_284, DoubleToStr(ld_144, 3), g_fontsize_152);
            if (gi_116 == 1) {
               ObjectCreate("HarPat8w" + g_count_284, OBJ_FIBO, 0, Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1], Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
               ObjectCreate("HarPat9w" + g_count_284, OBJ_FIBO, 0, Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2], Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1]);
            }
            ObjectCreate("HarPat10w" + g_count_284, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1]);
            ObjectSetText("HarPat10w" + g_count_284, "A     ", g_fontsize_148);
            ObjectCreate("HarPat11w" + g_count_284, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2]);
            ObjectSetText("HarPat11w" + g_count_284, "B     ", g_fontsize_148);
            ObjectCreate("HarPat12w" + g_count_284, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3]);
            ObjectSetText("HarPat12w" + g_count_284, "C     ", g_fontsize_148);
            ObjectCreate("HarPat13w" + g_count_284, OBJ_TEXT, 0, Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
            ObjectSetText("HarPat13w" + g_count_284, "D     ", g_fontsize_148);
            if (Show_Target_Fibo_Old == 1) ObjectCreate("HarPat20w", OBJ_FIBO, 0, Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3], Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
         }
         ObjectSet("HarPat0m" + g_count_280, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat1m" + g_count_280, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat2m" + g_count_280, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat3m" + g_count_280, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat4m" + g_count_280, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat5m" + g_count_280, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat15m" + g_count_280, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat16m" + g_count_280, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat0m" + g_count_280, OBJPROP_COLOR, Red);
         ObjectSet("HarPat1m" + g_count_280, OBJPROP_COLOR, Red);
         ObjectSet("HarPat2m" + g_count_280, OBJPROP_COLOR, Red);
         ObjectSet("HarPat3m" + g_count_280, OBJPROP_COLOR, Red);
         ObjectSet("HarPat4m" + g_count_280, OBJPROP_COLOR, Blue);
         ObjectSet("HarPat5m" + g_count_280, OBJPROP_COLOR, Blue);
         ObjectSet("HarPat6m" + g_count_280, OBJPROP_COLOR, Blue);
         ObjectSet("HarPat7m" + g_count_280, OBJPROP_COLOR, Blue);
         ObjectSet("HarPat8m" + g_count_280, OBJPROP_COLOR, Green);
         ObjectSet("HarPat9m" + g_count_280, OBJPROP_COLOR, Green);
         ObjectSet("HarPat10m" + g_count_280, OBJPROP_COLOR, DarkViolet);
         ObjectSet("HarPat11m" + g_count_280, OBJPROP_COLOR, DarkViolet);
         ObjectSet("HarPat12m" + g_count_280, OBJPROP_COLOR, DarkViolet);
         ObjectSet("HarPat13m" + g_count_280, OBJPROP_COLOR, DarkViolet);
         ObjectSet("HarPat14m" + g_count_280, OBJPROP_COLOR, DarkViolet);
         ObjectSet("HarPat15m" + g_count_280, OBJPROP_COLOR, Blue);
         ObjectSet("HarPat16m" + g_count_280, OBJPROP_COLOR, Blue);
         ObjectSet("HarPat17m" + g_count_280, OBJPROP_COLOR, Blue);
         ObjectSet("HarPat18m" + g_count_280, OBJPROP_COLOR, Blue);
         ObjectSet("HarPat19m" + g_count_280, OBJPROP_COLOR, Green);
         ObjectSet("HarPat20m", OBJPROP_COLOR, Blue);
         ObjectSet("HarPat21m" + g_count_280, OBJPROP_COLOR, PowderBlue);
         ObjectSet("HarPat22m" + g_count_280, OBJPROP_COLOR, LightPink);
         ObjectSet("HarPat0m" + g_count_280, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPat1m" + g_count_280, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPat2m" + g_count_280, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPat3m" + g_count_280, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPat4m" + g_count_280, OBJPROP_WIDTH, 0);
         ObjectSet("HarPat5m" + g_count_280, OBJPROP_WIDTH, 0);
         ObjectSet("HarPat4m" + g_count_280, OBJPROP_STYLE, STYLE_DOT);
         ObjectSet("HarPat5m" + g_count_280, OBJPROP_STYLE, STYLE_DOT);
         ObjectSet("HarPat8m" + g_count_280, OBJPROP_STYLE, STYLE_DASHDOTDOT);
         ObjectSet("HarPat9m" + g_count_280, OBJPROP_STYLE, STYLE_DOT);
         ObjectSet("HarPat15m" + g_count_280, OBJPROP_STYLE, STYLE_DOT);
         ObjectSet("HarPat16m" + g_count_280, OBJPROP_STYLE, STYLE_DOT);
         ObjectSet("HarPat19m" + g_count_280, OBJPROP_STYLE, STYLE_DASH);
         ObjectSet("HarPat20m", OBJPROP_STYLE, STYLE_DOT);
         ObjectSet("HarPat8m" + g_count_280, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat9m" + g_count_280, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat19m" + g_count_280, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat20m", OBJPROP_RAY, FALSE);
         ObjectSet("HarPat0w" + g_count_284, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat1w" + g_count_284, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat2w" + g_count_284, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat3w" + g_count_284, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat4w" + g_count_284, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat5w" + g_count_284, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat15w" + g_count_284, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat16w" + g_count_284, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat0w" + g_count_284, OBJPROP_COLOR, Blue);
         ObjectSet("HarPat1w" + g_count_284, OBJPROP_COLOR, Blue);
         ObjectSet("HarPat2w" + g_count_284, OBJPROP_COLOR, Blue);
         ObjectSet("HarPat3w" + g_count_284, OBJPROP_COLOR, Blue);
         ObjectSet("HarPat4w" + g_count_284, OBJPROP_COLOR, Red);
         ObjectSet("HarPat5w" + g_count_284, OBJPROP_COLOR, Red);
         ObjectSet("HarPat6w" + g_count_284, OBJPROP_COLOR, Red);
         ObjectSet("HarPat7w" + g_count_284, OBJPROP_COLOR, Red);
         ObjectSet("HarPat8w" + g_count_284, OBJPROP_COLOR, Green);
         ObjectSet("HarPat9w" + g_count_284, OBJPROP_COLOR, Green);
         ObjectSet("HarPat10w" + g_count_284, OBJPROP_COLOR, Black);
         ObjectSet("HarPat11w" + g_count_284, OBJPROP_COLOR, Black);
         ObjectSet("HarPat12w" + g_count_284, OBJPROP_COLOR, Black);
         ObjectSet("HarPat13w" + g_count_284, OBJPROP_COLOR, Black);
         ObjectSet("HarPat14w" + g_count_284, OBJPROP_COLOR, Black);
         ObjectSet("HarPat15w" + g_count_284, OBJPROP_COLOR, Red);
         ObjectSet("HarPat16w" + g_count_284, OBJPROP_COLOR, Red);
         ObjectSet("HarPat17w" + g_count_284, OBJPROP_COLOR, Red);
         ObjectSet("HarPat18w" + g_count_284, OBJPROP_COLOR, Red);
         ObjectSet("HarPat19w" + g_count_284, OBJPROP_COLOR, Green);
         ObjectSet("HarPat20w", OBJPROP_COLOR, Red);
         ObjectSet("HarPat21w" + g_count_284, OBJPROP_COLOR, PowderBlue);
         ObjectSet("HarPat22w" + g_count_284, OBJPROP_COLOR, LightPink);
         ObjectSet("HarPat0w" + g_count_284, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPat1w" + g_count_284, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPat2w" + g_count_284, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPat3w" + g_count_284, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPat4w" + g_count_284, OBJPROP_WIDTH, 0);
         ObjectSet("HarPat5w" + g_count_284, OBJPROP_WIDTH, 0);
         ObjectSet("HarPat4w" + g_count_284, OBJPROP_STYLE, STYLE_DOT);
         ObjectSet("HarPat5w" + g_count_284, OBJPROP_STYLE, STYLE_DOT);
         ObjectSet("HarPat8w" + g_count_284, OBJPROP_STYLE, STYLE_DASHDOTDOT);
         ObjectSet("HarPat9w" + g_count_284, OBJPROP_STYLE, STYLE_DOT);
         ObjectSet("HarPat15w" + g_count_284, OBJPROP_STYLE, STYLE_DOT);
         ObjectSet("HarPat16w" + g_count_284, OBJPROP_STYLE, STYLE_DOT);
         ObjectSet("HarPat19w" + g_count_284, OBJPROP_STYLE, STYLE_DASH);
         ObjectSet("HarPat20w", OBJPROP_STYLE, STYLE_DOT);
         ObjectSet("HarPat8w" + g_count_284, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat9w" + g_count_284, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat19w" + g_count_284, OBJPROP_RAY, FALSE);
         ObjectSet("HarPat20w", OBJPROP_RAY, FALSE);
      }
      if (gi_112 == 1) {
         if (gda_240[l_count_328 - 3] > gda_240[l_count_328 - 5] && gda_240[l_count_328 - 3] > gda_240[l_count_328 - 4] && gda_240[l_count_328 - 3] > gda_240[l_count_328 - 2] &&
            gda_240[l_count_328 - 3] > gda_240[l_count_328 - 1] && gda_240[l_count_328 - 3] > gda_240[l_count_328 - 0] && gda_240[l_count_328 - 3] > gda_240[l_count_328 - 6] &&
            gda_240[l_count_328 - 1] > gda_240[l_count_328 - 2] && gda_240[l_count_328 - 5] > gda_240[l_count_328 - 2] && gda_240[l_count_328 - 1] > gda_240[l_count_328 - 4] &&
            gda_240[l_count_328 - 5] > gda_240[l_count_328 - 4] && gda_240[l_count_328 - 2] > gda_240[l_count_328 - 0] && gda_240[l_count_328 - 4] > gda_240[l_count_328 - 0] &&
            gda_240[l_count_328 - 6] > 0.0) {
            g_count_288++;
            ObjectCreate("HarPatHSm0" + g_count_288, OBJ_TREND, 0, Time[gia_236[l_count_328 - 0]], gda_240[l_count_328 - 0], Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1]);
            ObjectCreate("HarPatHSm1" + g_count_288, OBJ_TREND, 0, Time[gia_236[l_count_328 - 1]], gda_240[l_count_328 - 1], Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2]);
            ObjectCreate("HarPatHSm2" + g_count_288, OBJ_TREND, 0, Time[gia_236[l_count_328 - 2]], gda_240[l_count_328 - 2], Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3]);
            ObjectCreate("HarPatHSm3" + g_count_288, OBJ_TREND, 0, Time[gia_236[l_count_328 - 3]], gda_240[l_count_328 - 3], Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4]);
            ObjectCreate("HarPatHSm4" + g_count_288, OBJ_TREND, 0, Time[gia_236[l_count_328 - 4]], gda_240[l_count_328 - 4], Time[gia_236[l_count_328 - 5]], gda_240[l_count_328 - 5]);
            ObjectCreate("HarPatHSm5" + g_count_288, OBJ_TREND, 0, Time[gia_236[l_count_328 - 5]], gda_240[l_count_328 - 5], Time[gia_236[l_count_328 - 6]], gda_240[l_count_328 - 6]);
         }
         if (gda_240[l_count_328 - 3] < gda_240[l_count_328 - 5] && gda_240[l_count_328 - 3] < gda_240[l_count_328 - 4] && gda_240[l_count_328 - 3] < gda_240[l_count_328 - 2] &&
            gda_240[l_count_328 - 3] < gda_240[l_count_328 - 1] && gda_240[l_count_328 - 3] < gda_240[l_count_328 - 0] && gda_240[l_count_328 - 3] < gda_240[l_count_328 - 6] &&
            gda_240[l_count_328 - 1] < gda_240[l_count_328 - 2] && gda_240[l_count_328 - 5] < gda_240[l_count_328 - 2] && gda_240[l_count_328 - 1] < gda_240[l_count_328 - 4] &&
            gda_240[l_count_328 - 5] < gda_240[l_count_328 - 4] && gda_240[l_count_328 - 2] < gda_240[l_count_328 - 0] && gda_240[l_count_328 - 4] < gda_240[l_count_328 - 0] &&
            gda_240[l_count_328 - 6] > 0.0) {
            g_count_292++;
            ObjectCreate("HarPatHSw0" + g_count_292, OBJ_TREND, 0, Time[gia_272[l_count_328 - 0]], gda_276[l_count_328 - 0], Time[gia_272[l_count_328 - 1]], gda_276[l_count_328 - 1]);
            ObjectCreate("HarPatHSw1" + g_count_292, OBJ_TREND, 0, Time[gia_272[l_count_328 - 1]], gda_276[l_count_328 - 1], Time[gia_272[l_count_328 - 2]], gda_276[l_count_328 - 2]);
            ObjectCreate("HarPatHSw2" + g_count_292, OBJ_TREND, 0, Time[gia_272[l_count_328 - 2]], gda_276[l_count_328 - 2], Time[gia_272[l_count_328 - 3]], gda_276[l_count_328 - 3]);
            ObjectCreate("HarPatHSw3" + g_count_292, OBJ_TREND, 0, Time[gia_272[l_count_328 - 3]], gda_276[l_count_328 - 3], Time[gia_272[l_count_328 - 4]], gda_276[l_count_328 - 4]);
            ObjectCreate("HarPatHSw4" + g_count_292, OBJ_TREND, 0, Time[gia_272[l_count_328 - 4]], gda_276[l_count_328 - 4], Time[gia_272[l_count_328 - 5]], gda_276[l_count_328 - 5]);
            ObjectCreate("HarPatHSw5" + g_count_292, OBJ_TREND, 0, Time[gia_272[l_count_328 - 5]], gda_276[l_count_328 - 5], Time[gia_272[l_count_328 - 6]], gda_276[l_count_328 - 6]);
         }
         ObjectSet("HarPatHSm0" + g_count_288, OBJPROP_RAY, FALSE);
         ObjectSet("HarPatHSm1" + g_count_288, OBJPROP_RAY, FALSE);
         ObjectSet("HarPatHSm2" + g_count_288, OBJPROP_RAY, FALSE);
         ObjectSet("HarPatHSm3" + g_count_288, OBJPROP_RAY, FALSE);
         ObjectSet("HarPatHSm4" + g_count_288, OBJPROP_RAY, FALSE);
         ObjectSet("HarPatHSm5" + g_count_288, OBJPROP_RAY, FALSE);
         ObjectSet("HarPatHSm0" + g_count_288, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPatHSm1" + g_count_288, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPatHSm2" + g_count_288, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPatHSm3" + g_count_288, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPatHSm4" + g_count_288, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPatHSm5" + g_count_288, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPatHSm0" + g_count_288, OBJPROP_COLOR, Green);
         ObjectSet("HarPatHSm1" + g_count_288, OBJPROP_COLOR, Green);
         ObjectSet("HarPatHSm2" + g_count_288, OBJPROP_COLOR, Green);
         ObjectSet("HarPatHSm3" + g_count_288, OBJPROP_COLOR, Green);
         ObjectSet("HarPatHSm4" + g_count_288, OBJPROP_COLOR, Green);
         ObjectSet("HarPatHSm5" + g_count_288, OBJPROP_COLOR, Green);
         ObjectSet("HarPatHSw0" + g_count_292, OBJPROP_RAY, FALSE);
         ObjectSet("HarPatHSw1" + g_count_292, OBJPROP_RAY, FALSE);
         ObjectSet("HarPatHSw2" + g_count_292, OBJPROP_RAY, FALSE);
         ObjectSet("HarPatHSw3" + g_count_292, OBJPROP_RAY, FALSE);
         ObjectSet("HarPatHSw4" + g_count_292, OBJPROP_RAY, FALSE);
         ObjectSet("HarPatHSw5" + g_count_292, OBJPROP_RAY, FALSE);
         ObjectSet("HarPatHSw0" + g_count_292, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPatHSw1" + g_count_292, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPatHSw2" + g_count_292, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPatHSw3" + g_count_292, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPatHSw4" + g_count_292, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPatHSw5" + g_count_292, OBJPROP_WIDTH, g_width_144);
         ObjectSet("HarPatHSw0" + g_count_292, OBJPROP_COLOR, Yellow);
         ObjectSet("HarPatHSw1" + g_count_292, OBJPROP_COLOR, Yellow);
         ObjectSet("HarPatHSw2" + g_count_292, OBJPROP_COLOR, Yellow);
         ObjectSet("HarPatHSw3" + g_count_292, OBJPROP_COLOR, Yellow);
         ObjectSet("HarPatHSw4" + g_count_292, OBJPROP_COLOR, Yellow);
         ObjectSet("HarPatHSw5" + g_count_292, OBJPROP_COLOR, Yellow);
      }
   }
   if (HP_Predict_Pattern == 1) {
      ld_152 = MathAbs(gda_240[3] - gda_240[2]);
      ld_160 = gda_240[2] - ld_152 / 100.0 * (gd_128 - 100.0);
      ld_168 = gda_240[2] - ld_152 / 100.0 * (gd_136 - 100.0);
      if (gda_240[2] < gda_240[3] && gda_240[1] > gda_240[2] && gda_240[1] <= gda_240[3] && gia_236[3] > gia_236[2] && gia_236[2] > gia_236[1]) {
         gi_296 = 1;
         gia_256[0] = 0;
         g_ibuf_200[gia_236[0]] = 33;
         g_ibuf_204[gia_256[0]] = gda_260[0];
         g_ibuf_208[gia_236[0]] = gda_240[1];
         if (MathAbs(gda_240[2] - gda_240[1]) / Point / (MathAbs(gda_240[2] - gda_240[3]) / Point + 0.0000001) <= 0.707) gda_260[0] = ld_160;
         else gda_260[0] = ld_168;
         if (gda_240[3] > gda_240[4] && gda_240[2] > gda_240[4] && gda_240[1] > gda_240[4] && gia_236[4] > gia_236[3]) {
            gi_296 = 2;
            g_ibuf_200[gia_236[0]] = 44;
            g_ibuf_204[gia_256[0]] = gda_260[0];
            g_ibuf_208[gia_236[0]] = gda_240[1];
            if (gi_120 == 1) {
               ObjectCreate("HarPat21mp", OBJ_TRIANGLE, 0, Time[gia_236[4]], gda_240[4], Time[gia_236[3]], gda_240[3], Time[gia_236[2]], gda_240[2]);
               ObjectCreate("HarPat22mp", OBJ_TRIANGLE, 0, Time[gia_236[2]], gda_240[2], Time[gia_236[1]], gda_240[1], Time[gia_248[0]], gda_260[0]);
            }
            ObjectCreate("HarPat0mp", OBJ_TREND, 0, Time[gia_236[4]], gda_240[4], Time[gia_236[3]], gda_240[3]);
            ObjectCreate("HarPat14mp", OBJ_TEXT, 0, Time[gia_236[4]], gda_240[4]);
            ObjectSetText("HarPat14mp", "x    ", g_fontsize_148);
            ObjectCreate("HarPat15mp", OBJ_TREND, 0, Time[gia_236[4]], gda_240[4], Time[gia_236[2]], gda_240[2]);
            ObjectCreate("HarPat16mp", OBJ_TREND, 0, Time[gia_236[4]], gda_240[4], Time[gia_256[0]], gda_260[0]);
            ObjectCreate("HarPat17mp", OBJ_TEXT, 0, Time[gia_236[2] - (gia_236[2] - gia_236[4]) / 2], gda_240[2] - (gda_240[2] - gda_240[4]) / 2.0);
            ObjectCreate("HarPat18mp", OBJ_TEXT, 0, Time[gia_236[4] - (gia_236[4] - gia_256[0]) / 2], gda_240[4] - (gda_240[4] - gda_260[0]) / 2.0);
            ld_176 = MathAbs(gda_240[3] - gda_240[2]) / Point / (MathAbs(gda_240[3] - gda_240[4]) / Point);
            ld_184 = MathAbs(gda_260[0] - gda_240[3]) / Point / (MathAbs(gda_240[3] - gda_240[4]) / Point);
            ObjectSetText("HarPat17mp", DoubleToStr(ld_176, 3), g_fontsize_152);
            ObjectSetText("HarPat18mp", DoubleToStr(ld_184, 3), g_fontsize_152);
            if (gi_116 == 1) {
               ObjectCreate("HarPat19mp", OBJ_FIBO, 0, Time[gia_236[4]], gda_240[4], Time[gia_236[3]], gda_240[3]);
               ObjectDelete("HarPat20m");
               ObjectDelete("HarPat20w");
            }
            gs_312 = " Buy at point D :  " + gda_260[0];
         }
         ObjectCreate("HarPat1mp", OBJ_TREND, 0, Time[gia_236[3]], gda_240[3], Time[gia_236[2]], gda_240[2]);
         ObjectCreate("HarPat2mp", OBJ_TREND, 0, Time[gia_236[2]], gda_240[2], Time[gia_236[1]], gda_240[1]);
         ObjectCreate("HarPat3mp", OBJ_TREND, 0, Time[gia_236[1]], gda_240[1], Time[gia_256[0]], gda_260[0]);
         ObjectCreate("HarPat4mp", OBJ_TREND, 0, Time[gia_236[3]], gda_240[3], Time[gia_236[1]], gda_240[1]);
         ObjectCreate("HarPat5mp", OBJ_TREND, 0, Time[gia_236[2]], gda_240[2], Time[gia_256[0]], gda_260[0]);
         ObjectCreate("HarPat6mp", OBJ_TEXT, 0, Time[gia_236[3] - (gia_236[3] - gia_236[1]) / 2], gda_240[3] - (gda_240[3] - gda_240[1]) / 2.0);
         ObjectCreate("HarPat7mp", OBJ_TEXT, 0, Time[gia_236[2] - (gia_236[2] - gia_256[0]) / 2], gda_240[2] - (gda_240[2] - gda_260[0]) / 2.0);
         ld_192 = MathAbs(gda_240[2] - gda_240[1]) / Point / (MathAbs(gda_240[2] - gda_240[3]) / Point + 0.0000001);
         ld_200 = MathAbs(gda_260[0] - gda_240[3]) / Point / (MathAbs(gda_240[2] - gda_240[3]) / Point + 0.0000001);
         ObjectSetText("HarPat6mp", DoubleToStr(ld_192, 3), g_fontsize_152);
         ObjectSetText("HarPat7mp", DoubleToStr(ld_200, 3), g_fontsize_152);
         if (gi_116 == 1) {
            ObjectCreate("HarPat8mp", OBJ_FIBO, 0, Time[gia_236[3]], gda_240[3], Time[gia_256[0]], gda_260[0]);
            ObjectCreate("HarPat9mp", OBJ_FIBO, 0, Time[gia_236[2]], gda_240[2], Time[gia_236[3]], gda_240[3]);
         }
         if (Show_Target_Fibo_P == 1) {
            ObjectCreate("HarPat20mp", OBJ_FIBO, 0, Time[gia_236[1]], gda_240[1], Time[gia_256[0]], gda_260[0]);
            ObjectDelete("HarPat20m");
            ObjectDelete("HarPat20w");
         }
         ObjectCreate("HarPat10mp", OBJ_TEXT, 0, Time[gia_236[3]], gda_240[3]);
         ObjectSetText("HarPat10mp", "a     ", g_fontsize_148);
         ObjectCreate("HarPat11mp", OBJ_TEXT, 0, Time[gia_236[2]], gda_240[2]);
         ObjectSetText("HarPat11mp", "b   ", g_fontsize_148);
         ObjectCreate("HarPat12mp", OBJ_TEXT, 0, Time[gia_236[1]], gda_240[1]);
         ObjectSetText("HarPat12mp", "c    ", g_fontsize_148);
         ObjectCreate("HarPat13mp", OBJ_TEXT, 0, Time[gia_256[0]], gda_260[0]);
         ObjectSetText("HarPat13mp", "d   ", g_fontsize_148);
         if (High[iHighest(NULL, 0, MODE_HIGH, gia_236[1], 0)] > gda_240[1] && gi_108 == 1) {
            ObjectDelete("HarPat0mp");
            ObjectDelete("HarPat1mp");
            ObjectDelete("HarPat2mp");
            ObjectDelete("HarPat3mp");
            ObjectDelete("HarPat4mp");
            ObjectDelete("HarPat5mp");
            ObjectDelete("HarPat6mp");
            ObjectDelete("HarPat7mp");
            ObjectDelete("HarPat8mp");
            ObjectDelete("HarPat9mp");
            ObjectDelete("HarPat10mp");
            ObjectDelete("HarPat11mp");
            ObjectDelete("HarPat12mp");
            ObjectDelete("HarPat13mp");
            ObjectDelete("HarPat14mp");
            ObjectDelete("HarPat15mp");
            ObjectDelete("HarPat16mp");
            ObjectDelete("HarPat17mp");
            ObjectDelete("HarPat18mp");
            ObjectDelete("HarPat19mp");
            ObjectDelete("HarPat20mp");
            ObjectDelete("HarPat21mp");
            ObjectDelete("HarPat22mp");
            gi_296 = 0;
            g_ibuf_200[gia_236[0]] = 0;
         }
         if ((gda_260[0] > Bid && gda_260[0] > Ask) || (gda_240[1] < Bid && gda_240[1] < Ask)) g_ibuf_200[gia_236[0]] = -1;
      }
      ld_208 = MathAbs(gda_240[2] - gda_240[3]);
      ld_216 = gda_240[2] + ld_208 / 100.0 * (gd_128 - 100.0);
      ld_224 = gda_240[2] + ld_208 / 100.0 * (gd_136 - 100.0);
      if (gda_240[2] > gda_240[3] && gda_240[1] < gda_240[2] && gda_240[1] >= gda_240[3] && gia_236[3] > gia_236[2] && gia_236[2] > gia_236[1]) {
         gi_300 = 1;
         gia_248[0] = 0;
         g_ibuf_212[gia_236[0]] = 33;
         g_ibuf_216[gia_248[0]] = gda_252[0];
         g_ibuf_220[gia_236[0]] = gda_240[1];
         if (MathAbs(gda_240[2] - gda_240[1]) / Point / (MathAbs(gda_240[2] - gda_240[3]) / Point + 0.0000001) <= 0.707) gda_252[0] = ld_216;
         else gda_252[0] = ld_224;
         if (gda_240[3] < gda_240[4] && gda_240[2] < gda_240[4] && gda_240[1] < gda_240[4] && gia_236[4] > gia_236[3]) {
            gi_300 = 2;
            g_ibuf_212[gia_236[0]] = 44;
            g_ibuf_216[gia_248[0]] = gda_252[0];
            g_ibuf_220[gia_236[0]] = gda_240[1];
            if (gi_120 == 1) {
               ObjectCreate("HarPat21wp", OBJ_TRIANGLE, 0, Time[gia_236[4]], gda_240[4], Time[gia_236[3]], gda_240[3], Time[gia_236[2]], gda_240[2]);
               ObjectCreate("HarPat22wp", OBJ_TRIANGLE, 0, Time[gia_236[2]], gda_240[2], Time[gia_236[1]], gda_240[1], Time[gia_248[0]], gda_252[0]);
            }
            ObjectCreate("HarPat0wp", OBJ_TREND, 0, Time[gia_236[4]], gda_240[4], Time[gia_236[3]], gda_240[3]);
            ObjectCreate("HarPat14wp", OBJ_TEXT, 0, Time[gia_236[4]], gda_240[4]);
            ObjectSetText("HarPat14wp", "X     ", g_fontsize_148);
            ObjectCreate("HarPat15wp", OBJ_TREND, 0, Time[gia_236[4]], gda_240[4], Time[gia_236[2]], gda_240[2]);
            ObjectCreate("HarPat16wp", OBJ_TREND, 0, Time[gia_236[4]], gda_240[4], Time[gia_248[0]], gda_252[0]);
            ObjectCreate("HarPat17wp", OBJ_TEXT, 0, Time[gia_236[2] - (gia_236[2] - gia_236[4]) / 2], gda_240[2] - (gda_240[2] - gda_240[4]) / 2.0);
            ObjectCreate("HarPat18wp", OBJ_TEXT, 0, Time[gia_236[4] - (gia_236[4] - gia_248[0]) / 2], gda_240[4] - (gda_240[4] - gda_252[0]) / 2.0);
            ld_232 = MathAbs(gda_240[2] - gda_240[3]) / Point / (MathAbs(gda_240[4] - gda_240[3]) / Point);
            ld_240 = MathAbs(gda_252[0] - gda_240[3]) / Point / (MathAbs(gda_240[4] - gda_240[3]) / Point);
            ObjectSetText("HarPat17wp", DoubleToStr(ld_232, 3), g_fontsize_152);
            ObjectSetText("HarPat18wp", DoubleToStr(ld_240, 3), g_fontsize_152);
            if (gi_116 == 1) {
               ObjectCreate("HarPat19wp", OBJ_FIBO, 0, Time[gia_236[3]], gda_240[3], Time[gia_236[4]], gda_240[4]);
               ObjectDelete("HarPat20m");
               ObjectDelete("HarPat20w");
            }
            gs_312 = " Sell at point D :  " + gda_252[0];
         }
         ObjectCreate("HarPat1wp", OBJ_TREND, 0, Time[gia_236[3]], gda_240[3], Time[gia_236[2]], gda_240[2]);
         ObjectCreate("HarPat2wp", OBJ_TREND, 0, Time[gia_236[2]], gda_240[2], Time[gia_236[1]], gda_240[1]);
         ObjectCreate("HarPat3wp", OBJ_TREND, 0, Time[gia_236[1]], gda_240[1], Time[gia_248[0]], gda_252[0]);
         ObjectCreate("HarPat4wp", OBJ_TREND, 0, Time[gia_236[3]], gda_240[3], Time[gia_236[1]], gda_240[1]);
         ObjectCreate("HarPat5wp", OBJ_TREND, 0, Time[gia_236[2]], gda_240[2], Time[gia_248[0]], gda_252[0]);
         ObjectCreate("HarPat6wp", OBJ_TEXT, 0, Time[gia_236[3] - (gia_236[3] - gia_236[1]) / 2], gda_240[3] - (gda_240[3] - gda_240[1]) / 2.0);
         ObjectCreate("HarPat7wp", OBJ_TEXT, 0, Time[gia_236[2] - (gia_236[2] - gia_248[0]) / 2], gda_240[2] - (gda_240[2] - gda_252[0]) / 2.0);
         ld_248 = MathAbs(gda_240[2] - gda_240[1]) / Point / (MathAbs(gda_240[2] - gda_240[3]) / Point + 0.0000001);
         ld_256 = MathAbs(gda_252[0] - gda_240[3]) / Point / (MathAbs(gda_240[2] - gda_240[3]) / Point + 0.0000001);
         ObjectSetText("HarPat6wp", DoubleToStr(ld_248, 3), g_fontsize_152);
         ObjectSetText("HarPat7wp", DoubleToStr(ld_256, 3), g_fontsize_152);
         if (gi_116 == 1) {
            ObjectCreate("HarPat8wp", OBJ_FIBO, 0, Time[gia_236[3]], gda_240[3], Time[gia_248[0]], gda_252[0]);
            ObjectCreate("HarPat9wp", OBJ_FIBO, 0, Time[gia_236[2]], gda_240[2], Time[gia_236[3]], gda_240[3]);
         }
         if (Show_Target_Fibo_P == 1) ObjectCreate("HarPat20wp", OBJ_FIBO, 0, Time[gia_236[1]], gda_240[1], Time[gia_248[0]], gda_252[0]);
         ObjectCreate("HarPat10wp", OBJ_TEXT, 0, Time[gia_236[3]], gda_240[3]);
         ObjectSetText("HarPat10wp", "A   ", g_fontsize_148);
         ObjectCreate("HarPat11wp", OBJ_TEXT, 0, Time[gia_236[2]], gda_240[2]);
         ObjectSetText("HarPat11wp", "B     ", g_fontsize_148);
         ObjectCreate("HarPat12wp", OBJ_TEXT, 0, Time[gia_236[1]], gda_240[1]);
         ObjectSetText("HarPat12wp", "C   ", g_fontsize_148);
         ObjectCreate("HarPat13wp", OBJ_TEXT, 0, Time[gia_248[0]], gda_252[0]);
         ObjectSetText("HarPat13wp", "D     ", g_fontsize_148);
         if (Low[iLowest(NULL, 0, MODE_LOW, gia_236[1], 0)] < gda_240[1] && gi_108 == 1) {
            ObjectDelete("HarPat0wp");
            ObjectDelete("HarPat1wp");
            ObjectDelete("HarPat2wp");
            ObjectDelete("HarPat3wp");
            ObjectDelete("HarPat4wp");
            ObjectDelete("HarPat5wp");
            ObjectDelete("HarPat6wp");
            ObjectDelete("HarPat7wp");
            ObjectDelete("HarPat8wp");
            ObjectDelete("HarPat9wp");
            ObjectDelete("HarPat10wp");
            ObjectDelete("HarPat11wp");
            ObjectDelete("HarPat12wp");
            ObjectDelete("HarPat13wp");
            ObjectDelete("HarPat14wp");
            ObjectDelete("HarPat15wp");
            ObjectDelete("HarPat16wp");
            ObjectDelete("HarPat17wp");
            ObjectDelete("HarPat18wp");
            ObjectDelete("HarPat19wp");
            ObjectDelete("HarPat20wp");
            ObjectDelete("HarPat21wp");
            ObjectDelete("HarPat22wp");
            gi_300 = 0;
            g_ibuf_212[gia_236[0]] = 0;
         }
         if ((gda_252[0] < Bid && gda_252[0] < Ask) || (gda_240[1] > Bid && gda_240[1] > Ask)) g_ibuf_212[gia_236[0]] = -1;
      }
      ObjectSet("HarPat0mp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat1mp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat2mp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat3mp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat4mp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat5mp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat15mp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat16mp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat0mp", OBJPROP_COLOR, Orange);
      ObjectSet("HarPat1mp", OBJPROP_COLOR, Orange);
      ObjectSet("HarPat2mp", OBJPROP_COLOR, Orange);
      ObjectSet("HarPat3mp", OBJPROP_COLOR, Orange);
      ObjectSet("HarPat4mp", OBJPROP_COLOR, Blue);
      ObjectSet("HarPat5mp", OBJPROP_COLOR, Blue);
      ObjectSet("HarPat6mp", OBJPROP_COLOR, Blue);
      ObjectSet("HarPat7mp", OBJPROP_COLOR, Blue);
      ObjectSet("HarPat8mp", OBJPROP_COLOR, Green);
      ObjectSet("HarPat9mp", OBJPROP_COLOR, Green);
      ObjectSet("HarPat10mp", OBJPROP_COLOR, Black);
      ObjectSet("HarPat11mp", OBJPROP_COLOR, Black);
      ObjectSet("HarPat12mp", OBJPROP_COLOR, Black);
      ObjectSet("HarPat13mp", OBJPROP_COLOR, Black);
      ObjectSet("HarPat14mp", OBJPROP_COLOR, Black);
      ObjectSet("HarPat15mp", OBJPROP_COLOR, Blue);
      ObjectSet("HarPat16mp", OBJPROP_COLOR, Blue);
      ObjectSet("HarPat17mp", OBJPROP_COLOR, Blue);
      ObjectSet("HarPat18mp", OBJPROP_COLOR, Blue);
      ObjectSet("HarPat19mp", OBJPROP_COLOR, Green);
      ObjectSet("HarPat20mp", OBJPROP_COLOR, Blue);
      ObjectSet("HarPat21mp", OBJPROP_COLOR, PowderBlue);
      ObjectSet("HarPat22mp", OBJPROP_COLOR, LightPink);
      ObjectSet("HarPat0mp", OBJPROP_WIDTH, g_width_144);
      ObjectSet("HarPat1mp", OBJPROP_WIDTH, g_width_144);
      ObjectSet("HarPat2mp", OBJPROP_WIDTH, g_width_144);
      ObjectSet("HarPat3mp", OBJPROP_WIDTH, g_width_144);
      ObjectSet("HarPat4mp", OBJPROP_WIDTH, 0);
      ObjectSet("HarPat5mp", OBJPROP_WIDTH, 0);
      ObjectSet("HarPat4mp", OBJPROP_STYLE, STYLE_DOT);
      ObjectSet("HarPat5mp", OBJPROP_STYLE, STYLE_DOT);
      ObjectSet("HarPat8mp", OBJPROP_STYLE, STYLE_DASHDOTDOT);
      ObjectSet("HarPat9mp", OBJPROP_STYLE, STYLE_DOT);
      ObjectSet("HarPat15mp", OBJPROP_STYLE, STYLE_DOT);
      ObjectSet("HarPat16mp", OBJPROP_STYLE, STYLE_DOT);
      ObjectSet("HarPat19mp", OBJPROP_STYLE, STYLE_DASH);
      ObjectSet("HarPat20mp", OBJPROP_STYLE, STYLE_DOT);
      ObjectSet("HarPat8mp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat9mp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat19mp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat20mp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat0wp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat1wp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat2wp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat3wp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat4wp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat5wp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat15wp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat16wp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat0wp", OBJPROP_COLOR, DarkViolet);
      ObjectSet("HarPat1wp", OBJPROP_COLOR, DarkViolet);
      ObjectSet("HarPat2wp", OBJPROP_COLOR, DarkViolet);
      ObjectSet("HarPat3wp", OBJPROP_COLOR, DarkViolet);
      ObjectSet("HarPat4wp", OBJPROP_COLOR, Red);
      ObjectSet("HarPat5wp", OBJPROP_COLOR, Red);
      ObjectSet("HarPat6wp", OBJPROP_COLOR, Red);
      ObjectSet("HarPat7wp", OBJPROP_COLOR, Red);
      ObjectSet("HarPat8wp", OBJPROP_COLOR, Green);
      ObjectSet("HarPat9wp", OBJPROP_COLOR, Green);
      ObjectSet("HarPat10wp", OBJPROP_COLOR, Black);
      ObjectSet("HarPat11wp", OBJPROP_COLOR, Black);
      ObjectSet("HarPat12wp", OBJPROP_COLOR, Black);
      ObjectSet("HarPat13wp", OBJPROP_COLOR, Black);
      ObjectSet("HarPat14wp", OBJPROP_COLOR, Black);
      ObjectSet("HarPat15wp", OBJPROP_COLOR, Red);
      ObjectSet("HarPat16wp", OBJPROP_COLOR, Red);
      ObjectSet("HarPat17wp", OBJPROP_COLOR, Red);
      ObjectSet("HarPat18wp", OBJPROP_COLOR, Red);
      ObjectSet("HarPat19wp", OBJPROP_COLOR, Green);
      ObjectSet("HarPat20wp", OBJPROP_COLOR, Red);
      ObjectSet("HarPat21wp", OBJPROP_COLOR, PowderBlue);
      ObjectSet("HarPat22wp", OBJPROP_COLOR, LightPink);
      ObjectSet("HarPat0wp", OBJPROP_WIDTH, g_width_144);
      ObjectSet("HarPat1wp", OBJPROP_WIDTH, g_width_144);
      ObjectSet("HarPat2wp", OBJPROP_WIDTH, g_width_144);
      ObjectSet("HarPat3wp", OBJPROP_WIDTH, g_width_144);
      ObjectSet("HarPat4wp", OBJPROP_WIDTH, 0);
      ObjectSet("HarPat5wp", OBJPROP_WIDTH, 0);
      ObjectSet("HarPat4wp", OBJPROP_STYLE, STYLE_DOT);
      ObjectSet("HarPat5wp", OBJPROP_STYLE, STYLE_DOT);
      ObjectSet("HarPat8wp", OBJPROP_STYLE, STYLE_DASHDOTDOT);
      ObjectSet("HarPat9wp", OBJPROP_STYLE, STYLE_DOT);
      ObjectSet("HarPat15wp", OBJPROP_STYLE, STYLE_DOT);
      ObjectSet("HarPat16wp", OBJPROP_STYLE, STYLE_DOT);
      ObjectSet("HarPat19wp", OBJPROP_STYLE, STYLE_DASH);
      ObjectSet("HarPat20wp", OBJPROP_STYLE, STYLE_DOT);
      ObjectSet("HarPat8wp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat9wp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat19wp", OBJPROP_RAY, FALSE);
      ObjectSet("HarPat20wp", OBJPROP_RAY, FALSE);
   }
   if (gi_296 > 1 || gi_300 > 1 && gi_156 == 1 && MathMod(Minute(), Period()) == 0.0 && Seconds() <= 5 && gi_168 == FALSE) {
      Alert("Harmonic Pattern on: ", Symbol(), "   graph : ", Period() + "    " + TimeToStr(TimeCurrent()) + "  " + gs_312);
      gi_168 = TRUE;
      if (gi_160 == 1) {
         SendMail("Harmonic Pattern", "Harmonic Pattern  on  " + Symbol() + "  " + Period() + "    " + TimeToStr(TimeCurrent()) 
         + "\n\n   " + gs_312);
      }
   } else
      if (Seconds() < 10) gi_168 = FALSE;
   gi_296 = 0;
   gi_300 = 0;
   gi_unused_304 = 0;
   gi_unused_308 = 0;
   if (TimeCurrent() > gd_84 + 5.0 && MathMod(Minute(), Period()) == 0.0 && Seconds() <= 10 && gi_172 == FALSE) {
      Alert("Your version of this Indicator ! ( Harmonic Patterns.  ) has expired  \n Please Download new version ! ! !  ", Symbol(), "   ", Period());
      ObjectsDeleteAll(0, OBJ_TREND);
      ObjectsDeleteAll(0, OBJ_FIBO);
      ObjectsDeleteAll(0, OBJ_EXPANSION);
      ObjectsDeleteAll(0, OBJ_HLINE);
      ObjectsDeleteAll(0, OBJ_TEXT);
      ObjectsDeleteAll(0, 511);
      ObjectsDeleteAll(0, OBJ_VLINE);
      gi_172 = TRUE;
      DeleteObj_preD();
      DeleteObj_old();
   }
   if (Seconds() < 20) gi_172 = FALSE;
   ObjectsRedraw();
   return (0);
}