/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/

#property indicator_chart_window
#property indicator_buffers 2
#property indicator_color1 White
#property indicator_color2 White

extern int TimeFrame = 240;
double g_ibuf_80[];
double g_ibuf_84[];

int init() {
   SetIndexBuffer(0, g_ibuf_80);
   SetIndexStyle(0, DRAW_LINE);
   SetIndexBuffer(1, g_ibuf_84);
   SetIndexStyle(1, DRAW_LINE);
   IndicatorShortName("MTF_Trendenvelopes_v2(14)");
   SetIndexLabel(0, "Up");
   SetIndexLabel(1, "Dn");
   return (0);
}

int start() {
   int lia_0[];
   int li_16 = 0;
   int l_ind_counted_20 = IndicatorCounted();
   ArrayCopySeries(lia_0, 5, Symbol(), TimeFrame);
   int li_12 = Bars - l_ind_counted_20 + TimeFrame / Period();
   int l_index_4 = 0;
   li_16 = 0;
   while (l_index_4 < li_12) {
      if (Time[l_index_4] < lia_0[li_16]) li_16++;
      g_ibuf_80[l_index_4] = iCustom(NULL, TimeFrame, "TrendEnvelopes_v2", 0, li_16);
      g_ibuf_84[l_index_4] = iCustom(NULL, TimeFrame, "TrendEnvelopes_v2", 1, li_16);
      l_index_4++;
   }
   return (0);
}
