/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright " by cja "
#property link      " by cja "

#property indicator_chart_window

extern string Change_Multi_num_to_load_many = "indicators on the same chart ";
extern int Multi_num = 12345;
extern string IIIIIIIIIIIIIIIIIIIIIII = "<<<< CCI Period >>>>>>>>>>>>>>>>>>>>>>>>";
extern int CCI_Period = 14;
extern int CCI_Price = 0;
extern string IIIIIIIIIIIIIIIIIIIIIIIII = "<<<< Indicator Display Shift >>>>>>>>>>>>>>>>>>>>>";
extern int CCI_Window = 0;
extern int Shift_UP_DN = 0;
extern int Shift_Left_Right = 0;
extern string IIIIIIIIIIIIIIIIIIIIIIII = "<<<< Level Settings >>>>>>>>>>>>>>>>>>>>";
extern int UpperLevel = 250;
extern int LowerLevel = 250;
extern int UpperMidLevel = 100;
extern int LowerMidLevel = 100;
extern string IIIIIIIIIIIIIIIIIIIIIIIIIII = "<<<< CCI Lower Digit Levels >>>>>>>>>>>>>>>>";
extern bool Show_Digits = TRUE;
extern color Digit_Number_UPcolor = DodgerBlue;
extern color Digit_Number_DNcolor = OrangeRed;
extern color Digit_Number_ZEROcolor = Gray;
extern string IIIIIIIIIIIIIIIIIIIIIIIIII = "<<<< Label $ Border colors >>>>>>>>>>>>>>";
extern color Main_Title_color = SteelBlue;
extern color Minute_Label_color = LightSteelBlue;
extern color Border_color = LightSteelBlue;
extern string IIIIIIIIIIIIIIIIIIIIIIIIIIII = "<<<< Level colors >>>>>>>>>>>>>>>>>>>>>>";
extern color Level_Xtrme_Plus = CornflowerBlue;
extern color Level_Upper_Plus = RoyalBlue;
extern color Level_Mid_Plus = Blue;
extern color Level_Mid_Minus = Crimson;
extern color Level_Lower_Minus = Tomato;
extern color Level_Xtrme_Minus = Orange;
extern string IIIIIIIIIIIIIIIIIIIIIIIIIIIII = "<<<< No Signal color >>>>>>>>>>>>>>>>>>>>";
extern color CCI_NO_Signal_color = C'0x37,0x37,0x58';

int init() {
   return (0);
}

int deinit() {
   ObjectDelete("CCI_cja" + Multi_num + "");
   ObjectDelete("CCI_SignalLB" + Multi_num + "");
   ObjectDelete("CCI_SignalLB1" + Multi_num + "");
   ObjectDelete("CCI_SignalLB2" + Multi_num + "");
   ObjectDelete("CCI_SignalLB3" + Multi_num + "");
   ObjectDelete("CCI_SignalLB4" + Multi_num + "");
   ObjectDelete("CCI_SignalLB5" + Multi_num + "");
   ObjectDelete("CCI_SignalLB6" + Multi_num + "");
   ObjectDelete("CCI_SignalLB7" + Multi_num + "");
   ObjectDelete("CCI_Signalm1" + Multi_num + "");
   ObjectDelete("CCI_Signal1m1" + Multi_num + "");
   ObjectDelete("CCI_Signal2m1" + Multi_num + "");
   ObjectDelete("CCI_Signal3m1" + Multi_num + "");
   ObjectDelete("CCI_Signal4m1" + Multi_num + "");
   ObjectDelete("CCI_Signal5m1" + Multi_num + "");
   ObjectDelete("CCI_Signalm5" + Multi_num + "");
   ObjectDelete("CCI_Signal1m5" + Multi_num + "");
   ObjectDelete("CCI_Signal2m5" + Multi_num + "");
   ObjectDelete("CCI_Signal3m5" + Multi_num + "");
   ObjectDelete("CCI_Signal4m5" + Multi_num + "");
   ObjectDelete("CCI_Signal5m5" + Multi_num + "");
   ObjectDelete("CCI_Signalm15" + Multi_num + "");
   ObjectDelete("CCI_Signal1m15" + Multi_num + "");
   ObjectDelete("CCI_Signal2m15" + Multi_num + "");
   ObjectDelete("CCI_Signal3m15" + Multi_num + "");
   ObjectDelete("CCI_Signal4m15" + Multi_num + "");
   ObjectDelete("CCI_Signal5m15" + Multi_num + "");
   ObjectDelete("CCI_Signalm30" + Multi_num + "");
   ObjectDelete("CCI_Signal1m30" + Multi_num + "");
   ObjectDelete("CCI_Signal2m30" + Multi_num + "");
   ObjectDelete("CCI_Signal3m30" + Multi_num + "");
   ObjectDelete("CCI_Signal4m30" + Multi_num + "");
   ObjectDelete("CCI_Signal5m30" + Multi_num + "");
   ObjectDelete("CCI_Signalh1" + Multi_num + "");
   ObjectDelete("CCI_Signal1h1" + Multi_num + "");
   ObjectDelete("CCI_Signal2h1" + Multi_num + "");
   ObjectDelete("CCI_Signal3h1" + Multi_num + "");
   ObjectDelete("CCI_Signal4h1" + Multi_num + "");
   ObjectDelete("CCI_Signal5h1" + Multi_num + "");
   ObjectDelete("CCI_Signalh4" + Multi_num + "");
   ObjectDelete("CCI_Signal1h4" + Multi_num + "");
   ObjectDelete("CCI_Signal2h4" + Multi_num + "");
   ObjectDelete("CCI_Signal3h4" + Multi_num + "");
   ObjectDelete("CCI_Signal4h4" + Multi_num + "");
   ObjectDelete("CCI_Signal5h4" + Multi_num + "");
   ObjectDelete("CCI_SignalNo" + Multi_num + "");
   ObjectDelete("CCI_SignalNo1" + Multi_num + "");
   ObjectDelete("CCI_SignalNo2" + Multi_num + "");
   ObjectDelete("CCI_SignalNo3" + Multi_num + "");
   ObjectDelete("CCI_SignalNo4" + Multi_num + "");
   ObjectDelete("CCI_SignalNo5" + Multi_num + "");
   return (0);
}

int start() {
   color l_color_244;
   color l_color_248;
   color l_color_252;
   color l_color_256;
   color l_color_260;
   color l_color_264;
   int l_ind_counted_0 = IndicatorCounted();
   double l_icci_4 = iCCI(NULL, PERIOD_H4, CCI_Period, CCI_Price, 0);
   double l_icci_12 = iCCI(NULL, PERIOD_H1, CCI_Period, CCI_Price, 0);
   double l_icci_20 = iCCI(NULL, PERIOD_M30, CCI_Period, CCI_Price, 0);
   double l_icci_28 = iCCI(NULL, PERIOD_M15, CCI_Period, CCI_Price, 0);
   double l_icci_36 = iCCI(NULL, PERIOD_M5, CCI_Period, CCI_Price, 0);
   double l_icci_44 = iCCI(NULL, PERIOD_M1, CCI_Period, CCI_Price, 0);
   string l_text_52 = "";
   string l_text_60 = "";
   string l_text_68 = "";
   string l_text_76 = "";
   string l_text_84 = "";
   string l_text_92 = "";
   l_text_52 = "-";
   color l_color_100 = CCI_NO_Signal_color;
   l_text_52 = "-";
   color l_color_104 = CCI_NO_Signal_color;
   l_text_52 = "-";
   color l_color_108 = CCI_NO_Signal_color;
   l_text_52 = "-";
   color l_color_112 = CCI_NO_Signal_color;
   l_text_52 = "-";
   color l_color_116 = CCI_NO_Signal_color;
   l_text_52 = "-";
   color l_color_120 = CCI_NO_Signal_color;
   if (l_icci_44 > UpperLevel) {
      l_text_52 = "-";
      l_color_100 = Level_Xtrme_Plus;
   }
   if (l_icci_44 > UpperMidLevel && l_icci_44 <= UpperLevel) {
      l_text_52 = "-";
      l_color_104 = Level_Upper_Plus;
   }
   if (l_icci_44 > 0.0 && l_icci_44 <= UpperMidLevel) {
      l_text_52 = "-";
      l_color_108 = Level_Mid_Plus;
   }
   if (l_icci_44 <= 0.0 && l_icci_44 > (-LowerMidLevel)) {
      l_text_52 = "-";
      l_color_112 = Level_Mid_Minus;
   }
   if (l_icci_44 <= (-LowerMidLevel) && l_icci_44 > (-LowerLevel)) {
      l_text_52 = "-";
      l_color_116 = Level_Lower_Minus;
   }
   if (l_icci_44 <= -LowerLevel) {
      l_text_52 = "-";
      l_color_120 = Level_Xtrme_Minus;
   }
   l_text_60 = "-";
   color l_color_124 = CCI_NO_Signal_color;
   l_text_60 = "-";
   color l_color_128 = CCI_NO_Signal_color;
   l_text_60 = "-";
   color l_color_132 = CCI_NO_Signal_color;
   l_text_60 = "-";
   color l_color_136 = CCI_NO_Signal_color;
   l_text_60 = "-";
   color l_color_140 = CCI_NO_Signal_color;
   l_text_60 = "-";
   color l_color_144 = CCI_NO_Signal_color;
   if (l_icci_36 > UpperLevel) {
      l_text_60 = "-";
      l_color_124 = Level_Xtrme_Plus;
   }
   if (l_icci_36 > UpperMidLevel && l_icci_36 <= UpperLevel) {
      l_text_60 = "-";
      l_color_128 = Level_Upper_Plus;
   }
   if (l_icci_36 > 0.0 && l_icci_36 <= UpperMidLevel) {
      l_text_60 = "-";
      l_color_132 = Level_Mid_Plus;
   }
   if (l_icci_36 <= 0.0 && l_icci_36 > (-LowerMidLevel)) {
      l_text_60 = "-";
      l_color_136 = Level_Mid_Minus;
   }
   if (l_icci_36 <= (-LowerMidLevel) && l_icci_36 > (-LowerLevel)) {
      l_text_60 = "-";
      l_color_140 = Level_Lower_Minus;
   }
   if (l_icci_36 <= -LowerLevel) {
      l_text_60 = "-";
      l_color_144 = Level_Xtrme_Minus;
   }
   l_text_68 = "-";
   color l_color_148 = CCI_NO_Signal_color;
   l_text_68 = "-";
   color l_color_152 = CCI_NO_Signal_color;
   l_text_68 = "-";
   color l_color_156 = CCI_NO_Signal_color;
   l_text_68 = "-";
   color l_color_160 = CCI_NO_Signal_color;
   l_text_68 = "-";
   color l_color_164 = CCI_NO_Signal_color;
   l_text_68 = "-";
   color l_color_168 = CCI_NO_Signal_color;
   if (l_icci_28 > UpperLevel) {
      l_text_68 = "-";
      l_color_148 = Level_Xtrme_Plus;
   }
   if (l_icci_28 > UpperMidLevel && l_icci_28 <= UpperLevel) {
      l_text_68 = "-";
      l_color_152 = Level_Upper_Plus;
   }
   if (l_icci_28 > 0.0 && l_icci_28 <= UpperMidLevel) {
      l_text_68 = "-";
      l_color_156 = Level_Mid_Plus;
   }
   if (l_icci_28 <= 0.0 && l_icci_28 > (-LowerMidLevel)) {
      l_text_68 = "-";
      l_color_160 = Level_Mid_Minus;
   }
   if (l_icci_28 <= (-LowerMidLevel) && l_icci_28 > (-LowerLevel)) {
      l_text_68 = "-";
      l_color_164 = Level_Lower_Minus;
   }
   if (l_icci_28 <= -LowerLevel) {
      l_text_68 = "-";
      l_color_168 = Level_Xtrme_Minus;
   }
   l_text_76 = "-";
   color l_color_172 = CCI_NO_Signal_color;
   l_text_76 = "-";
   color l_color_176 = CCI_NO_Signal_color;
   l_text_76 = "-";
   color l_color_180 = CCI_NO_Signal_color;
   l_text_76 = "-";
   color l_color_184 = CCI_NO_Signal_color;
   l_text_76 = "-";
   color l_color_188 = CCI_NO_Signal_color;
   l_text_76 = "-";
   color l_color_192 = CCI_NO_Signal_color;
   if (l_icci_20 > UpperLevel) {
      l_text_76 = "-";
      l_color_172 = Level_Xtrme_Plus;
   }
   if (l_icci_20 > UpperMidLevel && l_icci_20 <= UpperLevel) {
      l_text_76 = "-";
      l_color_176 = Level_Upper_Plus;
   }
   if (l_icci_20 > 0.0 && l_icci_20 <= UpperMidLevel) {
      l_text_76 = "-";
      l_color_180 = Level_Mid_Plus;
   }
   if (l_icci_20 <= 0.0 && l_icci_20 > (-LowerMidLevel)) {
      l_text_76 = "-";
      l_color_184 = Level_Mid_Minus;
   }
   if (l_icci_20 <= (-LowerMidLevel) && l_icci_20 > (-LowerLevel)) {
      l_text_76 = "-";
      l_color_188 = Level_Lower_Minus;
   }
   if (l_icci_20 <= -LowerLevel) {
      l_text_76 = "-";
      l_color_192 = Level_Xtrme_Minus;
   }
   l_text_84 = "-";
   color l_color_196 = CCI_NO_Signal_color;
   l_text_84 = "-";
   color l_color_200 = CCI_NO_Signal_color;
   l_text_84 = "-";
   color l_color_204 = CCI_NO_Signal_color;
   l_text_84 = "-";
   color l_color_208 = CCI_NO_Signal_color;
   l_text_84 = "-";
   color l_color_212 = CCI_NO_Signal_color;
   l_text_84 = "-";
   color l_color_216 = CCI_NO_Signal_color;
   if (l_icci_12 > UpperLevel) {
      l_text_84 = "-";
      l_color_196 = Level_Xtrme_Plus;
   }
   if (l_icci_12 > UpperMidLevel && l_icci_12 <= UpperLevel) {
      l_text_84 = "-";
      l_color_200 = Level_Upper_Plus;
   }
   if (l_icci_12 > 0.0 && l_icci_12 <= UpperMidLevel) {
      l_text_84 = "-";
      l_color_204 = Level_Mid_Plus;
   }
   if (l_icci_12 <= 0.0 && l_icci_12 > (-LowerMidLevel)) {
      l_text_84 = "-";
      l_color_208 = Level_Mid_Minus;
   }
   if (l_icci_12 <= (-LowerMidLevel) && l_icci_12 > (-LowerLevel)) {
      l_text_84 = "-";
      l_color_212 = Level_Lower_Minus;
   }
   if (l_icci_12 <= -LowerLevel) {
      l_text_84 = "-";
      l_color_216 = Level_Xtrme_Minus;
   }
   l_text_92 = "-";
   color l_color_220 = CCI_NO_Signal_color;
   l_text_92 = "-";
   color l_color_224 = CCI_NO_Signal_color;
   l_text_92 = "-";
   color l_color_228 = CCI_NO_Signal_color;
   l_text_92 = "-";
   color l_color_232 = CCI_NO_Signal_color;
   l_text_92 = "-";
   color l_color_236 = CCI_NO_Signal_color;
   l_text_92 = "-";
   color l_color_240 = CCI_NO_Signal_color;
   if (l_icci_4 > UpperLevel) {
      l_text_92 = "-";
      l_color_220 = Level_Xtrme_Plus;
   }
   if (l_icci_4 > UpperMidLevel && l_icci_4 <= UpperLevel) {
      l_text_92 = "-";
      l_color_224 = Level_Upper_Plus;
   }
   if (l_icci_4 > 0.0 && l_icci_4 <= UpperMidLevel) {
      l_text_92 = "-";
      l_color_228 = Level_Mid_Plus;
   }
   if (l_icci_4 <= 0.0 && l_icci_4 > (-LowerMidLevel)) {
      l_text_92 = "-";
      l_color_232 = Level_Mid_Minus;
   }
   if (l_icci_4 <= (-LowerMidLevel) && l_icci_4 > (-LowerLevel)) {
      l_text_92 = "-";
      l_color_236 = Level_Lower_Minus;
   }
   if (l_icci_4 <= -LowerLevel) {
      l_text_92 = "-";
      l_color_240 = Level_Xtrme_Minus;
   }
   ObjectDelete("CCI_cja" + Multi_num + "");
   ObjectCreate("CCI_cja" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_cja" + Multi_num + "", "cja", 8, "Tahoma", DarkSlateGray);
   ObjectSet("CCI_cja" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_cja" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 155);
   ObjectSet("CCI_cja" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 32);
   ObjectDelete("CCI_SignalLB" + Multi_num + "");
   ObjectCreate("CCI_SignalLB" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_SignalLB" + Multi_num + "", "MTF CCI  " + CCI_Period + " ", 12, "Arial Bold", Main_Title_color);
   ObjectSet("CCI_SignalLB" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_SignalLB" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 40);
   ObjectSet("CCI_SignalLB" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 15);
   ObjectDelete("CCI_SignalLB1" + Multi_num + "");
   ObjectCreate("CCI_SignalLB1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_SignalLB1" + Multi_num + "", "M1  M5  M15  M30  H1  H4", 7, "Arial Bold", Minute_Label_color);
   ObjectSet("CCI_SignalLB1" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_SignalLB1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 35);
   ObjectSet("CCI_SignalLB1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 33);
   ObjectDelete("CCI_SignalLB2" + Multi_num + "");
   ObjectCreate("CCI_SignalLB2" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_SignalLB2" + Multi_num + "", "-------------------------------------------", 8, "Arial", Border_color);
   ObjectSet("CCI_SignalLB2" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_SignalLB2" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 25);
   ObjectSet("CCI_SignalLB2" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 38);
   ObjectDelete("CCI_SignalLB3" + Multi_num + "");
   ObjectCreate("CCI_SignalLB3" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_SignalLB3" + Multi_num + "", "" + UpperLevel + " ------------------------------------------", 7, "Arial", Border_color);
   ObjectSet("CCI_SignalLB3" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_SignalLB3" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 25);
   ObjectSet("CCI_SignalLB3" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 49);
   ObjectDelete("CCI_SignalLB4" + Multi_num + "");
   ObjectCreate("CCI_SignalLB4" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_SignalLB4" + Multi_num + "", "" + UpperMidLevel + " ------------------------------------------", 7, "Arial", Border_color);
   ObjectSet("CCI_SignalLB4" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_SignalLB4" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 25);
   ObjectSet("CCI_SignalLB4" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 59);
   ObjectDelete("CCI_SignalLB5" + Multi_num + "");
   ObjectCreate("CCI_SignalLB5" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_SignalLB5" + Multi_num + "", "0 ------------------------------------------", 7, "Arial", Border_color);
   ObjectSet("CCI_SignalLB5" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_SignalLB5" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 25);
   ObjectSet("CCI_SignalLB5" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 69);
   ObjectDelete("CCI_SignalLB6" + Multi_num + "");
   ObjectCreate("CCI_SignalLB6" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_SignalLB6" + Multi_num + "", "" + LowerMidLevel + " ------------------------------------------", 7, "Arial", Border_color);
   ObjectSet("CCI_SignalLB6" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_SignalLB6" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 25);
   ObjectSet("CCI_SignalLB6" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 79);
   ObjectDelete("CCI_SignalLB7" + Multi_num + "");
   ObjectCreate("CCI_SignalLB7" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_SignalLB7" + Multi_num + "", "" + LowerLevel + " ------------------------------------------", 7, "Arial", Border_color);
   ObjectSet("CCI_SignalLB7" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_SignalLB7" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 25);
   ObjectSet("CCI_SignalLB7" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 89);
   ObjectDelete("CCI_Signalm1" + Multi_num + "");
   ObjectCreate("CCI_Signalm1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signalm1" + Multi_num + "", l_text_52, 42, "Arial ", l_color_120);
   ObjectSet("CCI_Signalm1" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signalm1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 130);
   ObjectSet("CCI_Signalm1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 63);
   ObjectDelete("CCI_Signal1m1" + Multi_num + "");
   ObjectCreate("CCI_Signal1m1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal1m1" + Multi_num + "", l_text_52, 42, "Arial ", l_color_116);
   ObjectSet("CCI_Signal1m1" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal1m1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 130);
   ObjectSet("CCI_Signal1m1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 53);
   ObjectDelete("CCI_Signal2m1" + Multi_num + "");
   ObjectCreate("CCI_Signal2m1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal2m1" + Multi_num + "", l_text_52, 42, "Arial ", l_color_112);
   ObjectSet("CCI_Signal2m1" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal2m1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 130);
   ObjectSet("CCI_Signal2m1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 43);
   ObjectDelete("CCI_Signal3m1" + Multi_num + "");
   ObjectCreate("CCI_Signal3m1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal3m1" + Multi_num + "", l_text_52, 42, "Arial ", l_color_108);
   ObjectSet("CCI_Signal3m1" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal3m1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 130);
   ObjectSet("CCI_Signal3m1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 33);
   ObjectDelete("CCI_Signal4m1" + Multi_num + "");
   ObjectCreate("CCI_Signal4m1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal4m1" + Multi_num + "", l_text_52, 42, "Arial ", l_color_104);
   ObjectSet("CCI_Signal4m1" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal4m1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 130);
   ObjectSet("CCI_Signal4m1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 23);
   ObjectDelete("CCI_Signal5m1" + Multi_num + "");
   ObjectCreate("CCI_Signal5m1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal5m1" + Multi_num + "", l_text_52, 42, "Arial ", l_color_100);
   ObjectSet("CCI_Signal5m1" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal5m1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 130);
   ObjectSet("CCI_Signal5m1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 13);
   ObjectDelete("CCI_Signalm5" + Multi_num + "");
   ObjectCreate("CCI_Signalm5" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signalm5" + Multi_num + "", l_text_60, 42, "Arial ", l_color_144);
   ObjectSet("CCI_Signalm5" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signalm5" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 110);
   ObjectSet("CCI_Signalm5" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 63);
   ObjectDelete("CCI_Signal1m5" + Multi_num + "");
   ObjectCreate("CCI_Signal1m5" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal1m5" + Multi_num + "", l_text_60, 42, "Arial ", l_color_140);
   ObjectSet("CCI_Signal1m5" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal1m5" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 110);
   ObjectSet("CCI_Signal1m5" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 53);
   ObjectDelete("CCI_Signal2m5" + Multi_num + "");
   ObjectCreate("CCI_Signal2m5" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal2m5" + Multi_num + "", l_text_60, 42, "Arial ", l_color_136);
   ObjectSet("CCI_Signal2m5" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal2m5" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 110);
   ObjectSet("CCI_Signal2m5" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 43);
   ObjectDelete("CCI_Signal3m5" + Multi_num + "");
   ObjectCreate("CCI_Signal3m5" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal3m5" + Multi_num + "", l_text_60, 42, "Arial ", l_color_132);
   ObjectSet("CCI_Signal3m5" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal3m5" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 110);
   ObjectSet("CCI_Signal3m5" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 33);
   ObjectDelete("CCI_Signal4m5" + Multi_num + "");
   ObjectCreate("CCI_Signal4m5" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal4m5" + Multi_num + "", l_text_60, 42, "Arial ", l_color_128);
   ObjectSet("CCI_Signal4m5" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal4m5" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 110);
   ObjectSet("CCI_Signal4m5" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 23);
   ObjectDelete("CCI_Signal5m5" + Multi_num + "");
   ObjectCreate("CCI_Signal5m5" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal5m5" + Multi_num + "", l_text_60, 42, "Arial ", l_color_124);
   ObjectSet("CCI_Signal5m5" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal5m5" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 110);
   ObjectSet("CCI_Signal5m5" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 13);
   ObjectDelete("CCI_Signalm15" + Multi_num + "");
   ObjectCreate("CCI_Signalm15" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signalm15" + Multi_num + "", l_text_68, 42, "Arial ", l_color_168);
   ObjectSet("CCI_Signalm15" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signalm15" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 90);
   ObjectSet("CCI_Signalm15" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 63);
   ObjectDelete("CCI_Signal1m15" + Multi_num + "");
   ObjectCreate("CCI_Signal1m15" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal1m15" + Multi_num + "", l_text_68, 42, "Arial ", l_color_164);
   ObjectSet("CCI_Signal1m15" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal1m15" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 90);
   ObjectSet("CCI_Signal1m15" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 53);
   ObjectDelete("CCI_Signal2m15" + Multi_num + "");
   ObjectCreate("CCI_Signal2m15" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal2m15" + Multi_num + "", l_text_68, 42, "Arial ", l_color_160);
   ObjectSet("CCI_Signal2m15" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal2m15" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 90);
   ObjectSet("CCI_Signal2m15" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 43);
   ObjectDelete("CCI_Signal3m15" + Multi_num + "");
   ObjectCreate("CCI_Signal3m15" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal3m15" + Multi_num + "", l_text_68, 42, "Arial ", l_color_156);
   ObjectSet("CCI_Signal3m15" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal3m15" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 90);
   ObjectSet("CCI_Signal3m15" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 33);
   ObjectDelete("CCI_Signal4m15" + Multi_num + "");
   ObjectCreate("CCI_Signal4m15" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal4m15" + Multi_num + "", l_text_68, 42, "Arial ", l_color_152);
   ObjectSet("CCI_Signal4m15" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal4m15" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 90);
   ObjectSet("CCI_Signal4m15" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 23);
   ObjectDelete("CCI_Signal5m15" + Multi_num + "");
   ObjectCreate("CCI_Signal5m15" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal5m15" + Multi_num + "", l_text_68, 42, "Arial ", l_color_148);
   ObjectSet("CCI_Signal5m15" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal5m15" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 90);
   ObjectSet("CCI_Signal5m15" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 13);
   ObjectDelete("CCI_Signalm30" + Multi_num + "");
   ObjectCreate("CCI_Signalm30" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signalm30" + Multi_num + "", l_text_76, 42, "Arial ", l_color_192);
   ObjectSet("CCI_Signalm30" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signalm30" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 70);
   ObjectSet("CCI_Signalm30" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 63);
   ObjectDelete("CCI_Signal1m30" + Multi_num + "");
   ObjectCreate("CCI_Signal1m30" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal1m30" + Multi_num + "", l_text_76, 42, "Arial ", l_color_188);
   ObjectSet("CCI_Signal1m30" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal1m30" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 70);
   ObjectSet("CCI_Signal1m30" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 53);
   ObjectDelete("CCI_Signal2m30" + Multi_num + "");
   ObjectCreate("CCI_Signal2m30" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal2m30" + Multi_num + "", l_text_76, 42, "Arial ", l_color_184);
   ObjectSet("CCI_Signal2m30" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal2m30" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 70);
   ObjectSet("CCI_Signal2m30" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 43);
   ObjectDelete("CCI_Signal3m30" + Multi_num + "");
   ObjectCreate("CCI_Signal3m30" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal3m30" + Multi_num + "", l_text_76, 42, "Arial ", l_color_180);
   ObjectSet("CCI_Signal3m30" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal3m30" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 70);
   ObjectSet("CCI_Signal3m30" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 33);
   ObjectDelete("CCI_Signal4m30" + Multi_num + "");
   ObjectCreate("CCI_Signal4m30" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal4m30" + Multi_num + "", l_text_76, 42, "Arial ", l_color_176);
   ObjectSet("CCI_Signal4m30" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal4m30" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 70);
   ObjectSet("CCI_Signal4m30" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 23);
   ObjectDelete("CCI_Signal5m30" + Multi_num + "");
   ObjectCreate("CCI_Signal5m30" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal5m30" + Multi_num + "", l_text_76, 42, "Arial ", l_color_172);
   ObjectSet("CCI_Signal5m30" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal5m30" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 70);
   ObjectSet("CCI_Signal5m30" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 13);
   ObjectDelete("CCI_Signalh1" + Multi_num + "");
   ObjectCreate("CCI_Signalh1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signalh1" + Multi_num + "", l_text_84, 42, "Arial ", l_color_216);
   ObjectSet("CCI_Signalh1" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signalh1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 50);
   ObjectSet("CCI_Signalh1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 63);
   ObjectDelete("CCI_Signal1h1" + Multi_num + "");
   ObjectCreate("CCI_Signal1h1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal1h1" + Multi_num + "", l_text_84, 42, "Arial ", l_color_212);
   ObjectSet("CCI_Signal1h1" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal1h1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 50);
   ObjectSet("CCI_Signal1h1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 53);
   ObjectDelete("CCI_Signal2h1" + Multi_num + "");
   ObjectCreate("CCI_Signal2h1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal2h1" + Multi_num + "", l_text_84, 42, "Arial ", l_color_208);
   ObjectSet("CCI_Signal2h1" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal2h1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 50);
   ObjectSet("CCI_Signal2h1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 43);
   ObjectDelete("CCI_Signal3h1" + Multi_num + "");
   ObjectCreate("CCI_Signal3h1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal3h1" + Multi_num + "", l_text_84, 42, "Arial ", l_color_204);
   ObjectSet("CCI_Signal3h1" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal3h1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 50);
   ObjectSet("CCI_Signal3h1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 33);
   ObjectDelete("CCI_Signal4h1" + Multi_num + "");
   ObjectCreate("CCI_Signal4h1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal4h1" + Multi_num + "", l_text_84, 42, "Arial ", l_color_200);
   ObjectSet("CCI_Signal4h1" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal4h1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 50);
   ObjectSet("CCI_Signal4h1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 23);
   ObjectDelete("CCI_Signal5h1" + Multi_num + "");
   ObjectCreate("CCI_Signal5h1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal5h1" + Multi_num + "", l_text_84, 42, "Arial ", l_color_196);
   ObjectSet("CCI_Signal5h1" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal5h1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 50);
   ObjectSet("CCI_Signal5h1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 13);
   ObjectDelete("CCI_Signalh4" + Multi_num + "");
   ObjectCreate("CCI_Signalh4" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signalh4" + Multi_num + "", l_text_92, 42, "Arial ", l_color_240);
   ObjectSet("CCI_Signalh4" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signalh4" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 30);
   ObjectSet("CCI_Signalh4" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 63);
   ObjectDelete("CCI_Signal1h4" + Multi_num + "");
   ObjectCreate("CCI_Signal1h4" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal1h4" + Multi_num + "", l_text_92, 42, "Arial ", l_color_236);
   ObjectSet("CCI_Signal1h4" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal1h4" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 30);
   ObjectSet("CCI_Signal1h4" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 53);
   ObjectDelete("CCI_Signal2h4" + Multi_num + "");
   ObjectCreate("CCI_Signal2h4" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal2h4" + Multi_num + "", l_text_92, 42, "Arial ", l_color_232);
   ObjectSet("CCI_Signal2h4" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal2h4" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 30);
   ObjectSet("CCI_Signal2h4" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 43);
   ObjectDelete("CCI_Signal3h4" + Multi_num + "");
   ObjectCreate("CCI_Signal3h4" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal3h4" + Multi_num + "", l_text_92, 42, "Arial ", l_color_228);
   ObjectSet("CCI_Signal3h4" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal3h4" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 30);
   ObjectSet("CCI_Signal3h4" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 33);
   ObjectDelete("CCI_Signal4h4" + Multi_num + "");
   ObjectCreate("CCI_Signal4h4" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal4h4" + Multi_num + "", l_text_92, 42, "Arial ", l_color_224);
   ObjectSet("CCI_Signal4h4" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal4h4" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 30);
   ObjectSet("CCI_Signal4h4" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 23);
   ObjectDelete("CCI_Signal5h4" + Multi_num + "");
   ObjectCreate("CCI_Signal5h4" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
   ObjectSetText("CCI_Signal5h4" + Multi_num + "", l_text_92, 42, "Arial ", l_color_220);
   ObjectSet("CCI_Signal5h4" + Multi_num + "", OBJPROP_CORNER, 1);
   ObjectSet("CCI_Signal5h4" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 30);
   ObjectSet("CCI_Signal5h4" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 13);
   if (l_icci_44 == 0.0) l_color_244 = Digit_Number_ZEROcolor;
   if (l_icci_44 > 0.0) l_color_244 = Digit_Number_UPcolor;
   if (l_icci_44 < 0.0) l_color_244 = Digit_Number_DNcolor;
   if (l_icci_36 == 0.0) l_color_248 = Digit_Number_ZEROcolor;
   if (l_icci_36 > 0.0) l_color_248 = Digit_Number_UPcolor;
   if (l_icci_36 < 0.0) l_color_248 = Digit_Number_DNcolor;
   if (l_icci_28 == 0.0) l_color_252 = Digit_Number_ZEROcolor;
   if (l_icci_28 > 0.0) l_color_252 = Digit_Number_UPcolor;
   if (l_icci_28 < 0.0) l_color_252 = Digit_Number_DNcolor;
   if (l_icci_20 == 0.0) l_color_256 = Digit_Number_ZEROcolor;
   if (l_icci_20 > 0.0) l_color_256 = Digit_Number_UPcolor;
   if (l_icci_20 < 0.0) l_color_256 = Digit_Number_DNcolor;
   if (l_icci_12 == 0.0) l_color_260 = Digit_Number_ZEROcolor;
   if (l_icci_12 > 0.0) l_color_260 = Digit_Number_UPcolor;
   if (l_icci_12 < 0.0) l_color_260 = Digit_Number_DNcolor;
   if (l_icci_4 == 0.0) l_color_264 = Digit_Number_ZEROcolor;
   if (l_icci_4 > 0.0) l_color_264 = Digit_Number_UPcolor;
   if (l_icci_4 < 0.0) l_color_264 = Digit_Number_DNcolor;
   if (Show_Digits == TRUE) {
      ObjectDelete("CCI_SignalNo" + Multi_num + "");
      ObjectCreate("CCI_SignalNo" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
      ObjectSetText("CCI_SignalNo" + Multi_num + "", DoubleToStr(l_icci_44, Digits - 4), 7, "Arial ", l_color_244);
      ObjectSet("CCI_SignalNo" + Multi_num + "", OBJPROP_CORNER, 1);
      ObjectSet("CCI_SignalNo" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 134);
      ObjectSet("CCI_SignalNo" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 103);
      ObjectDelete("CCI_SignalNo1" + Multi_num + "");
      ObjectCreate("CCI_SignalNo1" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
      ObjectSetText("CCI_SignalNo1" + Multi_num + "", DoubleToStr(l_icci_36, Digits - 4), 7, "Arial ", l_color_248);
      ObjectSet("CCI_SignalNo1" + Multi_num + "", OBJPROP_CORNER, 1);
      ObjectSet("CCI_SignalNo1" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 114);
      ObjectSet("CCI_SignalNo1" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 103);
      ObjectDelete("CCI_SignalNo2" + Multi_num + "");
      ObjectCreate("CCI_SignalNo2" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
      ObjectSetText("CCI_SignalNo2" + Multi_num + "", DoubleToStr(l_icci_28, Digits - 4), 7, "Arial ", l_color_252);
      ObjectSet("CCI_SignalNo2" + Multi_num + "", OBJPROP_CORNER, 1);
      ObjectSet("CCI_SignalNo2" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 94);
      ObjectSet("CCI_SignalNo2" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 103);
      ObjectDelete("CCI_SignalNo3" + Multi_num + "");
      ObjectCreate("CCI_SignalNo3" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
      ObjectSetText("CCI_SignalNo3" + Multi_num + "", DoubleToStr(l_icci_20, Digits - 4), 7, "Arial ", l_color_256);
      ObjectSet("CCI_SignalNo3" + Multi_num + "", OBJPROP_CORNER, 1);
      ObjectSet("CCI_SignalNo3" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 74);
      ObjectSet("CCI_SignalNo3" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 103);
      ObjectDelete("CCI_SignalNo4" + Multi_num + "");
      ObjectCreate("CCI_SignalNo4" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
      ObjectSetText("CCI_SignalNo4" + Multi_num + "", DoubleToStr(l_icci_12, Digits - 4), 7, "Arial ", l_color_260);
      ObjectSet("CCI_SignalNo4" + Multi_num + "", OBJPROP_CORNER, 1);
      ObjectSet("CCI_SignalNo4" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 54);
      ObjectSet("CCI_SignalNo4" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 103);
      ObjectDelete("CCI_SignalNo5" + Multi_num + "");
      ObjectCreate("CCI_SignalNo5" + Multi_num + "", OBJ_LABEL, CCI_Window, 0, 0);
      ObjectSetText("CCI_SignalNo5" + Multi_num + "", DoubleToStr(l_icci_4, Digits - 4), 7, "Arial ", l_color_264);
      ObjectSet("CCI_SignalNo5" + Multi_num + "", OBJPROP_CORNER, 1);
      ObjectSet("CCI_SignalNo5" + Multi_num + "", OBJPROP_XDISTANCE, Shift_Left_Right + 34);
      ObjectSet("CCI_SignalNo5" + Multi_num + "", OBJPROP_YDISTANCE, Shift_UP_DN + 103);
   }
   return (0);
}
